image: node:18

variables:
  ARTIFACT_DOWNLOAD_ATTEMPTS: 2 # Number of retries for restoring saved artifacts.
  FORCE_COLOR: '1' # Whether to force colour output in compatible tooling.
  GET_SOURCES_ATTEMPTS: 2 # Number of retries for git commands.
  GIT_STRATEGY: fetch # How to pull submodules.
  GIT_SUBMODULE_STRATEGY: recursive # How to treat nested git submodules.
  RESTORE_CACHE_ATTEMPTS: 2 # Number of retries for restoring cached files.

stages:
  - prepare
  - test_jest
  - test_build
  - publish

# Installs all dependencies.
install:
  stage: prepare
  interruptible: true
  retry: 1
  dependencies: []
  artifacts:
    name: 'deps_$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
    when: on_success
    expire_in: 12h
  script:
    - npm install --no-progress --no-audit --no-fund --verbose
  # only:
  #   - merge_requests
  #   - develop
  #   - main

test_jest:
  stage: test_jest
  interruptible: true
  retry: 1
  dependencies:
    - install
  script:
    - npm run build:release || true
    - npm run test

test_build:
  stage: test_build
  interruptible: true
  retry: 1
  dependencies:
    - install
  script:
    - npm run build:release || true
    - ls
    - ls build
    - node build/src/main.js

# Publishes the package to npm.
publish:
  stage: publish
  interruptible: false
  dependencies:
    - install
  script:
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
    - npm run build:release || true
    - npm publish --verbose
  resource_group: 'deployment-$CI_COMMIT_REF_SLUG'
  # rules:
  #   - if: '$CI_DEPLOY_FREEZE != null'
  #     when: never
  #   - if: '$CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_REF_NAME != "develop"'
  #     when: never
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME == "develop"'
  #     when: never
  #   - when: on_success
