/*
 * Copyright 2023 Liu Weihao
 * 
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { readFileSync } from 'fs';
import { join } from 'path';
import { Big } from 'big.js';

import { Array_exprContext, ArrayExprContext, Assignment_exprContext, Atom_exprContext, 
    Break_keywordContext, Continue_keywordContext, ExpressionContext,  Function_args_exprContext, 
    Function_call_exprContext, Function_exprContext,  Function_return_exprContext, 
    FunctionCallExprContext, Import_exprContext, Operator_assignment_exprContext, 
    ParametersContext, RoundedBracketsExprContext,  ScriptContext, 
    Value_exprContext, ValueAtomExprContext } from "./antlr/CircuitScriptParser";
import { CircuitScriptVisitor } from "./antlr/CircuitScriptVisitor";
import { ExecutionContext } from "./execute";
import { Logger } from "./logger";
import { ClassComponent } from "./objects/ClassComponent";
import { Net } from "./objects/Net";
import { NumberOperator, NumberOperatorType, NumericValue, PercentageValue } from "./objects/ParamDefinition";
import { PinTypes } from "./objects/PinTypes";
import { CallableParameter, CFunctionOptions, ComplexType, 
    DeclaredReference, 
    Direction, 
    FunctionDefinedParameter, ReferenceType, UndeclaredReference, 
    ValueType } from "./objects/types";
import { ParserRuleContext, Token } from 'antlr4ng';
import { DoubleDelimiter1, GlobalDocumentName, ReferenceTypes } from './globals';
import { linkBuiltInMethods } from './builtinMethods';
import { resolveToNumericValue, throwWithContext } from './utils';
import { SequenceAction } from './objects/ExecutionScope';


export class BaseVisitor extends CircuitScriptVisitor<ComplexType | ReferenceType | any> {
    // See class CircuitScriptVisitor (generated by antlr4) to find method names

    // Contains the methods here, so that it is function based instead
    // of just lambdas/callbacks...

    indentLevel = 0;
    startingContext: ExecutionContext;
    executionStack: ExecutionContext[];

    // If true, then do not print out anything
    silent = false;

    logger: Logger;
    
    currentDirectory: string;
    defaultLibsPath: string;

    printStream: string[] = [];
    printToConsole = true;

    acceptedDirections = [Direction.Up, Direction.Down, 
        Direction.Right, Direction.Left];
        
    protected resultData = new Map<ParserRuleContext, any>;
    protected paramData = new Map<ParserRuleContext, any>;

    pinTypesList: string[] = [
        PinTypes.Any,
        PinTypes.Input,
        PinTypes.Output,
        PinTypes.IO,
        PinTypes.Power,
    ];

    onParseErrorHandler: OnErrorCallback | null = null;
    onSyntaxErrorHandler: OnErrorCallback | null = null;

    onImportFile = (visitor: BaseVisitor, filePath:string, fileData: string): 
        {hasError:boolean, hasParseError: boolean} => {
        
        throw "Import file not implemented"
    }

    constructor(silent = false, 
        onParseErrorHandler: OnErrorCallback | null = null,
        onSyntaxErrorHandler: OnErrorCallback | null = null,
        currentDirectory: string | null,
        defaultLibsPath: string) {
        
        super();
        this.logger = new Logger();
        this.onParseErrorHandler = onParseErrorHandler;
        this.onSyntaxErrorHandler = onSyntaxErrorHandler;

        this.startingContext = new ExecutionContext(
            DoubleDelimiter1,
            `${DoubleDelimiter1}.`,
            '/',
            0, 0, silent, 
            this.logger, null);

        const scope = this.startingContext.scope;

        // Start the sequence list with the cursor positioned at
        // the root node.
        scope.sequence.push([
            SequenceAction.At, scope.componentRoot!, scope.currentPin!
        ]);

        // Add the document global object, this is used to set the page size
        scope.variables.set(GlobalDocumentName, {});
        
        this.setupBuiltInFunctions(this.startingContext);
            
        this.executionStack = [this.startingContext];
        this.startingContext.resolveNet = 
            this.createNetResolver(this.executionStack);

        this.startingContext.resolveComponentPinNet = 
            this.createComponentPinNetResolver(this.executionStack);

        this.silent = silent;

        this.currentDirectory = currentDirectory!;
        this.defaultLibsPath = defaultLibsPath;
    }

    getExecutor(): ExecutionContext {
        return this.executionStack[this.executionStack.length - 1];
    }

    getRootExecutor(): ExecutionContext {
        return this.executionStack[0];
    }

    protected setupBuiltInFunctions(context: ExecutionContext): void {
        linkBuiltInMethods(context, this);
    }

    createNetResolver(executionStack: ExecutionContext[]): 
        (netName: string, netNamespace: string) => {found: boolean, net?: Net} {
        const resolveNet = (netName: string, netNamespace: string): 
            {found: boolean, net?: Net} => {
            // netNamespace is the current netNamespace where the net name is 
            // searching from.

            this.log('find net', netNamespace, netName);
            const reversed = [...executionStack].reverse();

            for (let i = 0; i < reversed.length; i++) {
                const context = reversed[i];
                const net = context.scope.getNetWithName(netName);

                if (net !== null && net.namespace === netNamespace) {
                    return {
                        found: true,
                        net,
                    }
                }
            }

            return {
                found: false
            }
        }

        return resolveNet;
    }
    
    createComponentPinNetResolver(executionStack: ExecutionContext[]):
        (component: ClassComponent, pin: number) => Net | null {

        return (component: ClassComponent, pin: number): Net | null => {
            const reversed = [...executionStack].reverse();

            for (let i = 0; i < reversed.length; i++) {
                const context = reversed[i];
                const net = context.scope.getNet(component, pin);
                if (net !== null) {
                    return net;
                }
            }

            return null;
        };
    }

    log(...params: any[]): void {
        const indentOutput = ''.padStart(this.indentLevel * 4, '    ');
        const indentLevelText = this.indentLevel.toString().padStart(3, ' ');

        const args = ['[' + indentLevelText + ']', indentOutput, ...params];
        
        this.logger.add(args.join(' '));

        if (!this.silent) {
            console.log.apply(null, args);
        }
    }

    log2(message: string): void {
        this.getExecutor().log(message);
    }

    visitScript = (ctx: ScriptContext): void => {
        this.log('===', 'start', '===');
        const result = this.visitChildren(ctx);
        this.log('===', 'end', '===');
        return result;
    }

    visitAssignment_expr = (ctx: Assignment_exprContext): void => {
        const reference = this.getReference(ctx.atom_expr()!);

        const ctxDataExpr = ctx.data_expr();
        this.visit(ctxDataExpr);
        const value = this.getResult(ctxDataExpr);

        const trailers = reference.trailers ?? [];

        if (trailers.length === 0) {
            if (value instanceof ClassComponent) {
                const variables = this.getExecutor().scope.variables;
                variables.set(reference.name!, value);

                this.getExecutor().scope.sequence.push(
                    [SequenceAction.Assign, reference.name, value]
                );

                this.log2(
                    `assigned '${reference.name}' to ClassComponent`,
                );
            } else {
                // No trailers, directly assign the reference name
                this.getExecutor().scope.variables.set(reference.name, value);
                this.log2(`assigned variable ${reference.name} to ${value}`);
            }
        } else {
            if (reference.parentValue instanceof ClassComponent){
                this.setInstanceParam(reference.parentValue, trailers, value);
                this.log2(`assigned component param ${reference.parentValue} trailers: ${trailers} value: ${value}`);
            } else if (reference.parentValue instanceof Object) {
                reference.parentValue[trailers.join('.')] = value;
                this.log2(`assigned object ${reference.parentValue} trailers: ${trailers} value: ${value}`)
            }
        }
        
        this.setResult(ctx, value);
    }

    visitOperator_assignment_expr = (ctx: Operator_assignment_exprContext): void => {
        const reference = this.getReference(ctx.atom_expr()!);

        const ctxDataExpr = ctx.data_expr();
        this.visit(ctxDataExpr);
        const value = this.getResult(ctxDataExpr);

        if (!reference.found) {
            this.throwWithContext(ctx, 'Undefined reference: ' + reference.name);
        }

        const trailers = reference.trailers ?? [];

        let currentValue: NumberOperatorType | number | null = null;

        if (trailers.length === 0) {
            currentValue = this.getExecutor().scope.variables.get(reference.name) as number;
        } else {
            if (reference.value instanceof ClassComponent) {
                currentValue = this.getInstanceParam(reference.value, trailers);
            } else if (reference.value instanceof Object) {
                currentValue = reference.value[trailers.join('.')];
            }
        }

        if (currentValue === null) {
            this.throwWithContext(ctx, 
                'Operator assignment failed: could not get value');
        }

        let newValue: number | NumberOperatorType = 0;

        const operator = new NumberOperator();
        if (ctx.AdditionAssign()) {
            newValue = operator.addition(
                currentValue as NumberOperatorType, value);
        } else if (ctx.MinusAssign()) {
            newValue = operator.subtraction(
                currentValue as NumberOperatorType, value);
        } else if (ctx.MultiplyAssign()) {
            newValue = operator.multiply(
                currentValue as NumberOperatorType, value);
        } else if (ctx.DivideAssign()) {
            newValue = operator.divide(
                currentValue as NumberOperatorType, value);
        } else if (ctx.ModulusAssign()) {
            newValue = operator.modulus(
                currentValue as NumberOperatorType, value);
        } else {
            this.throwWithContext(ctx,
                'Operator assignment failed: could not perform operator');
        }

        // Reassign back to value
        if (trailers.length === 0) {
            this.getExecutor().scope.variables.set(reference.name, newValue);
        } else {
            if (reference.value instanceof ClassComponent) {
                this.setInstanceParam(reference.value, trailers, newValue);
            } else if (reference.value instanceof Object) {
                reference.value[trailers.join('.')] = newValue;
            }
        }

        this.setResult(ctx, newValue);
    }

    private getReference(ctx: Atom_exprContext): ReferenceType {
        const atomStr = ctx.getText();

        // Do not allow the atom to have any parentheses in the assignment
        if (atomStr.indexOf('(') !== -1 || atomStr.indexOf(')') !== -1) {
            this.throwWithContext(ctx, "Invalid assignment expression!");
        }

        this.visit(ctx);
        const reference: ReferenceType = this.getResult(ctx);
        const { trailers = [] } = reference;

        const undefinedParentWithTrailers = trailers.length > 0
            && reference.parentValue === undefined;

        if (undefinedParentWithTrailers) {
            this.throwWithContext(ctx, 
                'Undefined reference: ' + reference.name + '.' + trailers.join('.'));
        }

        return reference;
    }

    visitAtom_expr = (ctx: Atom_exprContext): void => {
        const executor = this.getExecutor();

        const firstId = ctx.ID(0)!;
        const atomId = firstId.getText();

        let currentReference: ReferenceType;

        const idTrailers = [];
        if (ctx.ID().length > 1) {
            const idLength = ctx.ID().length;

            for (let i = 1; i < idLength; i++) {
                const tmpCtx = ctx.ID(i)!;
                idTrailers.push(tmpCtx.getText());
            }
        }

        // Check if it is hardcoded values, like the pin types.
        if (this.pinTypesList.indexOf(atomId) !== -1) {
            // Not sure if just returning the string is enough...
            currentReference = {
                found: true,
                value: atomId,
                type: ReferenceTypes.pinType,
            }
        } else {
            currentReference = executor.resolveVariable(
                this.executionStack, atomId, idTrailers);
        }

        if (currentReference.found && currentReference.type === 'instance' && idTrailers.length === 0) {
            const tmpComponent = currentReference.value as ClassComponent;

            // Copy the nets into the local net
            for (const [pinId, net] of tmpComponent.pinNets) {
                executor.scope.setNet(tmpComponent, pinId, net);
            }
        }

        // this.log2(`atomId: ${atomId} ${currentReference}`);

        if (ctx.parent instanceof ExpressionContext && !currentReference.found) {
            // If is an atom_expr and parent is just expression and no 
            // reference was found.
            this.throwWithContext(ctx, "Unknown symbol: " + atomId);
        }

        this.setResult(ctx, currentReference);
    }

    visitFunctionCallExpr = (ctx: FunctionCallExprContext):void => {
        const tmpCtx = ctx.function_call_expr();
        this.visit(tmpCtx);
        const result = this.getResult(tmpCtx);
        this.setResult(ctx, result);
    }

    visitFunction_call_expr = (ctx: Function_call_exprContext): void => {
        const executor = this.getExecutor();
        const atomId = ctx.ID().getText();
        let passedNetNamespace = null; // Assumed empty by default

        const netNameSpaceExpr = ctx.net_namespace_expr();
        if (netNameSpaceExpr) {
            this.visit(netNameSpaceExpr);
            passedNetNamespace = this.getResult(netNameSpaceExpr);
        }

        let currentReference: DeclaredReference = executor.resolveVariable(
            this.executionStack, atomId);

        if (ctx.trailer_expr().length > 0) {
            // Resolve all elements in the trailer expression list

            if (!currentReference.found) {
                this.throwWithContext(ctx,
                    "Unknown function name: " + atomId);
            }

            currentReference.trailers = [];

            ctx.trailer_expr().forEach(item => {
                const itemValue = item.getText();
                if (item.OPEN_PAREN() && item.CLOSE_PAREN()) {
                    let parameters: CallableParameter[] = [];

                    const ctxParameters = item.parameters();
                    if (ctxParameters) {
                        this.visit(ctxParameters);
                        parameters = this.getResult(ctxParameters);
                    }

                    const useNetNamespace = this.getNetNamespace(
                        executor.netNamespace,
                        passedNetNamespace,
                    )

                    try {
                        const [, functionResult] =
                            executor.callFunction(
                                currentReference.name,
                                parameters,
                                this.executionStack,
                                useNetNamespace);

                        currentReference = {
                            found: true,
                            value: functionResult,
                            type: (functionResult instanceof ClassComponent) ?
                                'instance' : 'value',
                        }
                    } catch (err) {
                        this.throwWithContext(ctx, err);
                    }

                } else {
                    currentReference.trailers.push(itemValue);
                }
            });
        }

        this.setResult(ctx, currentReference.value);
    }

    visitValue_expr = (ctx: Value_exprContext): void => {
        const sign = ctx.Minus() ? -1 : 1;

        const ctxIntegerValue = ctx.INTEGER_VALUE();
        const ctxDecimalValue = ctx.DECIMAL_VALUE();
        const ctxNumericValue = ctx.NUMERIC_VALUE();
        const ctxBooleanValue = ctx.BOOLEAN_VALUE();
        const ctxStringValue = ctx.STRING_VALUE();
        const ctxPercentageValue = ctx.PERCENTAGE_VALUE();
        
        let result: ValueType | null = null;

        if (ctxIntegerValue || ctxDecimalValue || ctxNumericValue) {
            if (ctxIntegerValue) {
                result = resolveToNumericValue(
                    (new Big(ctxIntegerValue.getText())).mul(new Big(sign))
                );
            } else if (ctxDecimalValue) {
                result = resolveToNumericValue(
                    (new Big(ctxDecimalValue.getText())).mul(new Big(sign))
                );

            } else if (ctxNumericValue) {
                const textExtra = ctx.Minus() ? '-' : '';
                result = new NumericValue(textExtra + ctxNumericValue.getText());

            }
        } else {
            if (sign === -1) {
                this.throwWithContext(ctx, "Invalid value");
            }
        }

        if (ctxBooleanValue) {
            const stringValue = ctxBooleanValue.getText();
            if (stringValue === 'true') {
                result = true;
            } else if (stringValue === 'false') {
                result = false;
            }

        } else if (ctxStringValue) {
            result = this.prepareStringValue(ctxStringValue.getText());

        } else if (ctxPercentageValue) {
            result = new PercentageValue(ctxPercentageValue.getText());

        }

        this.setResult(ctx, result);
    }

    visitValueAtomExpr = (ctx: ValueAtomExprContext): void => {
        let value: ComplexType = null;

        const ctxValueExpr = ctx.value_expr();
        const ctxAtomExpr = ctx.atom_expr();

        if (ctxValueExpr) {
            this.visit(ctxValueExpr);
            value = this.getResult(ctxValueExpr);

        } else if (ctxAtomExpr) {
            this.visit(ctxAtomExpr);
            const reference = this.getResult(ctxAtomExpr);

            if (!reference.found) {
                value = new UndeclaredReference(reference);
            } else {
                // This is the returned component from the function call
                if (reference.type && reference.type === ReferenceTypes.pinType) {
                    value = reference;
                } else {
                    if (reference.trailers && reference.trailers.length > 0) {
                        value = reference;
                    } else {
                        value = reference.value;
                    }
                }
            }
        }

        this.setResult(ctx, value);
    }

    visitFunction_args_expr = (ctx: Function_args_exprContext): void => {
        const defaultValuesProvided = ctx.value_expr();
        // The last <defaultValuesProvided> IDs have default values
        const IDs = ctx.ID(); // Do in reverse

        const boundary = IDs.length - defaultValuesProvided.length;

        const result: FunctionDefinedParameter[] = IDs.map((id, index) => {
            const idText = id.getText();
            if (index >= boundary) {
                const tmpCtx = defaultValuesProvided[index - boundary];
                this.visit(tmpCtx);
                const defaultValue = this.getResult(tmpCtx);
                return [idText, tmpCtx.start!, defaultValue];
            } else {
            return [idText, id.getSymbol()];
            }
        });

        this.setResult(ctx, result);
    }

    visitParameters = (ctx: ParametersContext): void => {
        const dataExpressions = ctx.data_expr();
        const keywordAssignmentExpressions = ctx.keyword_assignment_expr();

        const returnList: CallableParameter[] = [];

        dataExpressions.forEach((item, index) => {
            this.visit(item);
            const value = this.getResult(item); 
            returnList.push(['position', index, value]);
        });

        keywordAssignmentExpressions.forEach((item) => {
            this.visit(item);
            const [key, value] = this.getResult(item);
            returnList.push(['keyword', key, value]);
        });

        this.setResult(ctx, returnList);
    }

    visitImport_expr = (ctx: Import_exprContext): void => {
        const ID = ctx.ID().toString(); // filename
        this.log('import', ID);
        this.handleImportFile(ID, true, ctx);
        this.log('done import', ID);
    }

    visitFunction_return_expr = (ctx: Function_return_exprContext): void => {
        const executor = this.getExecutor();

        executor.log('return from function');

        const ctxDataExpr = ctx.data_expr();
        this.visit(ctxDataExpr)
        const returnValue = this.getResult(ctxDataExpr);

        executor.stopFurtherExpressions = true;
        executor.returnValue = returnValue;

        this.setResult(ctx, returnValue);
    }

    visitBreak_keyword = (ctx: Break_keywordContext): void => {
        // When the break keyword is encountered inside a branch, then leave the branch
        // without storing the final state. If used, the break should be
        // the last expression in the branch, any expressions after the break
        // will be skipped

        // this.getExecutor().breakBranch();
        // this.setResult(ctx, -1);

        const breakContext = this.getExecutor().getBreakContext();
        const currentResult = this.getResult(breakContext) ?? {};
        this.setResult(breakContext, {
            ...currentResult,
            breakSignal: true
        });
    }

    visitContinue_keyword = (ctx: Continue_keywordContext): void => {
        const breakContext = this.getExecutor().getBreakContext();
        const currentResult = this.getResult(breakContext) ?? {};
        this.setResult(breakContext, {
            ...currentResult,

            // continue is similar to break, except the loop is not 
            // completely stopped.
            breakSignal: true,
            continueSignal: true,
        });
    }

    visitArray_expr = (ctx: Array_exprContext): void => {
        const array = ctx.data_expr().map(item => {
            this.visit(item);
            return this.getResult(item);
        });

        this.setResult(ctx, array);
    }

    visitArrayExpr = (ctx: ArrayExprContext): void => {
        this.visit(ctx.array_expr());
        this.setResult(ctx, this.getResult(ctx.array_expr()));
    }

    protected setResult(ctx: ParserRuleContext, value: any): void {
        this.resultData.set(ctx, value);
    }

    protected getResult(ctx: ParserRuleContext): any {
        return this.resultData.get(ctx);
    }

    protected visitResult(ctx: ParserRuleContext): any {
        this.visit(ctx);
        return this.getResult(ctx);
    }

    protected handleImportFile(name: string, 
        throwErrors = true, ctx: ParserRuleContext | null =null): {

        hasError: boolean,
        hasParseError: boolean,
        pathExists: boolean
    } {

        let hasError = false;
        let hasParseError = false;
        let pathExists = false;

        const tmpFilePath = join(this.currentDirectory!, name + ".cst");
        this.log('importing path:', tmpFilePath);

        let fileData: string | null = null;
        let filePathUsed: string | null = null;

        try {
            fileData = readFileSync(tmpFilePath, { encoding: 'utf8' });
            filePathUsed = tmpFilePath;
            pathExists = true;
        } catch (err) {
            pathExists = false;
        }

        if (!pathExists) {
            // if path does not exist, then search default libs path
            try {
                const tmpFilePath2 = join(this.defaultLibsPath, name + ".cst");
                fileData = readFileSync(tmpFilePath2, { encoding: 'utf8' });
                filePathUsed = tmpFilePath2;
                pathExists = true;
            } catch (err) {
                pathExists = false;
            }
        }

        try {
            if (pathExists) {
                this.log('done reading imported file data');

                const importResult =
                    this.onImportFile(this, filePathUsed, fileData!,
                        this.onParseErrorHandler);

                hasError = importResult.hasError;
                hasParseError = importResult.hasParseError;
            }
        } catch (err) {
            this.log('Failed to import file: ', err.message);
        }

        let errorMessage = null;
        
        if (throwErrors && (hasError || hasParseError || !pathExists)) {
            if (!pathExists) {
                errorMessage = `File does not exist: ${name}`
            } else {
                errorMessage =  `Failed to import: ${name}`;
            }
        }

        if (errorMessage !== null && ctx){
            this.throwWithContext(ctx, errorMessage);
        }

        return {
            hasError,
            hasParseError,
            pathExists,
        }
    }

    visitRoundedBracketsExpr = (ctx: RoundedBracketsExprContext):void => {
        const ctxDataExpr = ctx.data_expr();
        this.visit(ctxDataExpr);
        const innerResult = this.getResult(ctxDataExpr);
        this.setResult(ctx, innerResult);
    }

    protected setupDefinedParameters(
        funcDefinedParameters: FunctionDefinedParameter[], 
        passedInParameters: CallableParameter[], 
        executor: ExecutionContext): void {
        
        // Check if the arguments match up
        for (let i = 0; i < funcDefinedParameters.length; i++) {
            const tmpFuncArg = funcDefinedParameters[i];

            if (i < passedInParameters.length) {
                const tmpPassedInArgs = passedInParameters[i];

                if (tmpPassedInArgs[0] === 'position') {
                    // If value is passed in as function parameter, then
                    // use it in the scope.
                    const variableName = tmpFuncArg[0];
                    executor.log(
                        'set variable in scope, var name: ',
                        variableName,
                    );
                    executor.scope.variables.set(
                        variableName,
                        tmpPassedInArgs[2],
                    );

                    if (tmpPassedInArgs[2] instanceof ClassComponent) {
                        const component  = tmpPassedInArgs[2];

                        // Add the component nets into the local scope
                        for(const [pinNumber, net] of component.pinNets){
                            executor.scope.setNet(component, pinNumber, net);
                        }
                    }
                } else if (tmpPassedInArgs[0] === 'keyword') {
                    const variableName = tmpPassedInArgs[1];
                    executor.log(
                        'set variable in scope, var name: ',
                        variableName
                    );

                    executor.scope.variables.set(
                        variableName,
                        tmpPassedInArgs[2]
                    );
                }

            } else if (tmpFuncArg.length === 3) {
                // Value was not provided to function, but a default 
                // value is provided.
                const variableName = tmpFuncArg[0];
                const defaultValue = tmpFuncArg[2];
                executor.log(
                    'set variable in scope, var name: ',
                    variableName,
                );
                executor.scope.variables.set(
                    variableName, defaultValue,
                );
            } else {
                throw `Invalid arguments got: ` + passedInParameters;
            }
        }
    }

    protected runExpressions(executor: ExecutionContext,
        expressions: ExpressionContext[] | Function_exprContext[]): ComplexType {

        let returnValue: ComplexType | null = null;

        // Track this context for a break signal
        const breakContext = executor.getBreakContext();

        // Execute the expressions within the context
        for (let i = 0; i < expressions.length; i++) {
            const expr = expressions[i];

            // The correct executor MUST be on the top/end of the stack!
            this.visit(expr);

            const { breakSignal = false } = this.getResult(breakContext) ?? {};
            if (breakSignal) {
                returnValue = executor.returnValue;
                break;
            }

            // If this flag is set, then do not parse anything further!
            if (executor.stopFurtherExpressions) {
                returnValue = executor.returnValue;
                break;
            }
        }

        return returnValue;
    }

    protected getNetNamespace(executorNetNamespace: string,
        passedNetNamespace: string | null): string {

        let result = executorNetNamespace;

        if (passedNetNamespace !== null && passedNetNamespace.length > 0) {
            // Either user specified '/' or '/_' to indicate the global
            // net namespace
            if (passedNetNamespace === '/' || passedNetNamespace === '_') {
                result = '';
            } else if (passedNetNamespace[0] === '+') {
                if (executorNetNamespace === '/') {
                    result = passedNetNamespace.slice(1)
                } else {
                    result = executorNetNamespace + passedNetNamespace.slice(2);
                }
            } else {
                result = passedNetNamespace;
            }

            result = result + '/';
        }

        return result;
    }

    protected setInstanceParam(object: ClassComponent, trailers: string[], value: any): void {
        const paramName = trailers[0];
        object.setParam(paramName, value);

        this.log2(
            `set instance ${object.instanceName} param ${paramName} to ${value}`);
    }

    protected getInstanceParam<T>(object: ClassComponent, trailers: string[]): T {
        const paramName = trailers[0];
        return object.getParam(paramName) as T;
    }

    protected enterNewChildContext(executionStack: ExecutionContext[],
        parentContext: ExecutionContext,
        executionContextName: string,
        options: CFunctionOptions,
        funcDefinedParameters: FunctionDefinedParameter[],
        passedInParameters: CallableParameter[]
    ): ExecutionContext {
        const { netNamespace = "" } = options;

        // Create a new execution context, so that the commands are executed only
        // within this context. Components and nets will be local to this context for now.
        const currentExecutionContext =
            executionStack[executionStack.length - 1];
        const executionLevel = currentExecutionContext.executionLevel;

        const executionContextNamespace = currentExecutionContext.namespace
            + executionContextName + ".";

        const newExecutor = new ExecutionContext(
            executionContextName,
            executionContextNamespace,
            netNamespace,
            executionLevel + 1,
            this.getExecutor().scope.indentLevel + 1,
            currentExecutionContext.silent,
            currentExecutionContext.logger,
            parentContext
        );

        // Add the execution context to the end of the execution stack
        executionStack.push(newExecutor);

        // Setup the params in the execution scope if there 
        // are any function parameters

        this.setupDefinedParameters(
            funcDefinedParameters,
            passedInParameters,
            newExecutor
        );

        return newExecutor;
    }

    protected prepareStringValue(value: string): string {
        return value.slice(1, value.length - 1);
    }

    protected throwWithContext(context: ParserRuleContext, message: string): void {
        throwWithContext(context, message);
    }
}

export type OnErrorCallback = 
    (token: Token, message: string, e: any | undefined) => void;