/*
 * Copyright 2023 Liu Weihao
 * 
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Big } from 'big.js';

import { Array_exprContext, ArrayExprContext, Assignment_exprContext, Atom_exprContext, 
    Break_keywordContext, Continue_keywordContext, ExpressionContext,  Function_args_exprContext, 
    Function_call_exprContext, Function_exprContext,  Function_return_exprContext, 
    FunctionCallExprContext, Import_exprContext, Operator_assignment_exprContext, 
    ParametersContext, RoundedBracketsExprContext,  ScriptContext, 
    Value_exprContext, ValueAtomExprContext } from "./antlr/CircuitScriptParser.js";
import { CircuitScriptVisitor } from "./antlr/CircuitScriptVisitor.js";
import { ExecutionContext } from "./execute.js";
import { Logger } from "./logger.js";
import { ClassComponent } from "./objects/ClassComponent.js";
import { Net } from "./objects/Net.js";
import { NumberOperator, NumberOperatorType, NumericValue, PercentageValue } from "./objects/ParamDefinition.js";
import { PinTypes } from "./objects/PinTypes.js";
import { CallableParameter, CFunctionOptions, ComplexType, 
    DeclaredReference, 
    Direction, 
    FunctionDefinedParameter, AnyReference, UndeclaredReference, 
    ValueType } from "./objects/types.js";
import { ParserRuleContext } from 'antlr4ng';
import { ComponentTypes, DoubleDelimiter1, GlobalDocumentName, ReferenceTypes } from './globals.js';
import { ExecutionWarning, isReference, prepareValue } from "./utils.js";
import { linkBuiltInMethods } from './builtinMethods.js';
import { BaseError, resolveToNumericValue, RuntimeExecutionError, throwWithContext } from './utils.js';
import { ExecutionScope, SequenceAction } from './objects/ExecutionScope.js';
import { NodeScriptEnvironment } from "./environment.js";

export class BaseVisitor extends CircuitScriptVisitor<ComplexType | AnyReference | any> {
    // See class CircuitScriptVisitor (generated by antlr4) to find method names

    // Contains the methods here, so that it is function based instead
    // of just lambdas/callbacks...

    indentLevel = 0;
    startingContext: ExecutionContext;
    executionStack: ExecutionContext[];

    // If true, then do not print out anything
    silent = false;

    logger: Logger;

    printStream: string[] = [];
    printToConsole = true;

    acceptedDirections = [Direction.Up, Direction.Down, 
        Direction.Right, Direction.Left];
        
    protected resultData = new Map<ParserRuleContext, any>;
    protected paramData = new Map<ParserRuleContext, any>;

    pinTypesList: string[] = [
        PinTypes.Any,
        PinTypes.Input,
        PinTypes.Output,
        PinTypes.IO,
        PinTypes.Power,
    ];

    onErrorHandler: OnErrorHandler | null = null;
    environment: NodeScriptEnvironment;

    protected importedFiles:ImportFile[] = [];

    protected warnings:ExecutionWarning[] = [];

    onImportFile = async (visitor: BaseVisitor, filePath:string, fileData: string, onErrorHandler: OnErrorHandler): 
        Promise<{hasError:boolean, hasParseError: boolean}> => {
        
        throw "Import file not implemented"
    }

    constructor(silent = false, 
        onErrorHandler: OnErrorHandler | null = null,
        environment: NodeScriptEnvironment) {
        
        super();
        this.logger = new Logger();
        this.onErrorHandler = onErrorHandler;
        this.environment = environment;

        this.startingContext = new ExecutionContext(
            DoubleDelimiter1,
            `${DoubleDelimiter1}.`,
            '/',
            0, 0, silent, 
            this.logger, 
            this.warnings,
            null);

        const scope = this.startingContext.scope;

        // Start the sequence list with the cursor positioned at
        // the root node.
        scope.sequence.push([
            SequenceAction.At, scope.componentRoot!, scope.currentPin!
        ]);

        // Add the document global object, this is used to set the page size
        scope.setVariable(GlobalDocumentName, {});
        
        this.setupBuiltInFunctions(this.startingContext);
            
        this.executionStack = [this.startingContext];
        this.startingContext.resolveNet = 
            this.createNetResolver(this.executionStack);

        this.startingContext.resolveComponentPinNet = 
            this.createComponentPinNetResolver(this.executionStack);

        this.silent = silent;
    }

    getExecutor(): ExecutionContext {
        return this.executionStack[this.executionStack.length - 1];
    }

    getScope(): ExecutionScope {
        return this.getExecutor().scope;
    }

    getRootExecutor(): ExecutionContext {
        return this.executionStack[0];
    }

    protected setupBuiltInFunctions(context: ExecutionContext): void {
        linkBuiltInMethods(context, this);
    }

    createNetResolver(executionStack: ExecutionContext[]): 
        (netName: string, netNamespace: string) => {found: boolean, net?: Net} {
        const resolveNet = (netName: string, netNamespace: string): 
            {found: boolean, net?: Net} => {
            // netNamespace is the current netNamespace where the net name is 
            // searching from.

            this.log('find net', netNamespace, netName);
            const reversed = [...executionStack].reverse();

            for (let i = 0; i < reversed.length; i++) {
                const context = reversed[i];
                const net = context.scope.getNetWithName(netName);

                if (net !== null && net.namespace === netNamespace) {
                    return {
                        found: true,
                        net,
                    }
                }
            }

            return {
                found: false
            }
        }

        return resolveNet;
    }
    
    createComponentPinNetResolver(executionStack: ExecutionContext[]):
        (component: ClassComponent, pin: number) => Net | null {

        return (component: ClassComponent, pin: number): Net | null => {
            const reversed = [...executionStack].reverse();

            for (let i = 0; i < reversed.length; i++) {
                const context = reversed[i];
                const net = context.scope.getNet(component, pin);
                if (net !== null) {
                    return net;
                }
            }

            return null;
        };
    }

    log(...params: any[]): void {
        const indentOutput = ''.padStart(this.indentLevel * 4, '    ');
        const indentLevelText = this.indentLevel.toString().padStart(3, ' ');

        const args = ['[' + indentLevelText + ']', indentOutput, ...params];
        
        this.logger.add(args.join(' '));

        if (!this.silent) {
            console.log.apply(null, args);
        }
    }

    log2(message: string): void {
        this.getExecutor().log(message);
    }

    async visitAsync(ctx: ParserRuleContext): Promise<void> {
        const result = await ctx.accept(this);
        return result;
    }

    visitScript = async (ctx: ScriptContext): Promise<void> => {
        this.log('===', 'start', '===');

        // Parse all import statements at the start since these might require
        // async calls
        const imports = ctx.import_expr();
        for (let i = 0; i < imports.length; i++) {
            const ctxImport = imports[i];
            const ID = ctxImport.ID().toString();
            await this.handleImportFile(ID, true, ctxImport);
        }

        const result = this.runExpressions(this.getExecutor(), ctx.expression());
        this.setResult(ctx, result);

        // If there are open blocks, then close them
        this.getExecutor().closeAllBlocks();

        this.log('===', 'end', '===');
    }

    visitAssignment_expr = (ctx: Assignment_exprContext): void => {
        const ctxAtom = ctx.atom_expr();
        const ctxFuncCall = ctx.function_call_expr();

        let leftSideReference: AnyReference;

        if (ctxAtom){
            leftSideReference = this.getReference(ctx.atom_expr()!);
        } else if (ctxFuncCall){
            // If left side is function call, then the result must
            // be a reference
            leftSideReference = this.visitResult(ctxFuncCall);
        }

        const ctxDataExpr = ctx.data_expr();
        const dataValue = this.visitResult(ctxDataExpr);
        const rhsValue = prepareValue(dataValue);

        const trailers = leftSideReference.trailers ?? [];
        
        const sequenceParts: (string|any)[] = [];

        if (trailers.length === 0) {
            if (rhsValue instanceof ClassComponent) {
                this.getScope().setVariable(leftSideReference.name!, rhsValue);
                sequenceParts.push(...['instance', leftSideReference.name, rhsValue]);

                this.log2(
                    `assigned '${leftSideReference.name}' to ClassComponent`,
                );
            } else {
                // No trailers, directly assign the reference name
                this.getScope().setVariable(leftSideReference.name, rhsValue);
                this.log2(`assigned variable ${leftSideReference.name} to ${rhsValue}`);

                sequenceParts.push(...['variable', leftSideReference.name, rhsValue]);
            }
        } else {
            if (leftSideReference.parentValue instanceof ClassComponent){
                this.setInstanceParam(leftSideReference.parentValue, trailers, rhsValue);
                this.log2(`assigned component param ${leftSideReference.parentValue} trailers: ${trailers} value: ${rhsValue}`);

                sequenceParts.push(...['instance', [leftSideReference.parentValue, trailers], rhsValue]);

                if (leftSideReference.parentValue.typeProp === ComponentTypes.net) {
                    // if a net component, there is onl 1 pin
                    const net = this.getScope().getNet(leftSideReference.parentValue, 1);
                    if (net) {
                        const trailerValue = trailers.join(".");
                        net.params.set(trailerValue, rhsValue);
                    }
                }

            } else if (leftSideReference.parentValue instanceof Object) {
                leftSideReference.parentValue[trailers.join('.')] = rhsValue;
                this.log2(`assigned object ${leftSideReference.parentValue} trailers: ${trailers} value: ${rhsValue}`)

                sequenceParts.push(...['variable', [leftSideReference.parentValue, trailers], rhsValue]);
            }
        }

        if (sequenceParts.length > 0) {
            this.getScope().sequence.push([
                SequenceAction.Assign, ...sequenceParts
            ]);
        }
        
        this.setResult(ctx, rhsValue);
    }

    visitOperator_assignment_expr = (ctx: Operator_assignment_exprContext): void => {
        const reference = this.getReference(ctx.atom_expr()!);

        const ctxDataExpr = ctx.data_expr();
        this.visit(ctxDataExpr);
        const value = this.getResult(ctxDataExpr);

        if (!reference.found) {
            this.throwWithContext(ctx, 'Undefined reference: ' + reference.name);
        }

        const trailers = reference.trailers ?? [];

        let currentValue: NumberOperatorType | number | null = null;

        if (trailers.length === 0) {
            currentValue = this.getExecutor().scope.variables.get(reference.name) as number;
        } else {
            if (reference.value instanceof ClassComponent) {
                currentValue = this.getInstanceParam(reference.value, trailers);
            } else if (reference.value instanceof Object) {
                currentValue = reference.value[trailers.join('.')];
            }
        }

        if (currentValue === null) {
            this.throwWithContext(ctx, 
                'Operator assignment failed: could not get value');
        }

        let newValue: number | NumberOperatorType = 0;

        const operator = new NumberOperator();
        if (ctx.AdditionAssign()) {
            newValue = operator.addition(
                currentValue as NumberOperatorType, value);
        } else if (ctx.MinusAssign()) {
            newValue = operator.subtraction(
                currentValue as NumberOperatorType, value);
        } else if (ctx.MultiplyAssign()) {
            newValue = operator.multiply(
                currentValue as NumberOperatorType, value);
        } else if (ctx.DivideAssign()) {
            newValue = operator.divide(
                currentValue as NumberOperatorType, value);
        } else if (ctx.ModulusAssign()) {
            newValue = operator.modulus(
                currentValue as NumberOperatorType, value);
        } else {
            this.throwWithContext(ctx,
                'Operator assignment failed: could not perform operator');
        }

        // Reassign back to value
        if (trailers.length === 0) {
            this.getExecutor().scope.setVariable(reference.name, newValue);
        } else {
            if (reference.value instanceof ClassComponent) {
                this.setInstanceParam(reference.value, trailers, newValue);
            } else if (reference.value instanceof Object) {
                reference.value[trailers.join('.')] = newValue;
            }
        }

        this.setResult(ctx, newValue);
    }

    private getReference(ctx: Atom_exprContext): AnyReference {
        const atomStr = ctx.getText();

        // Do not allow the atom to have any parentheses in the assignment
        if (atomStr.indexOf('(') !== -1 || atomStr.indexOf(')') !== -1) {
            this.throwWithContext(ctx, "Invalid assignment expression!");
        }

        const reference: AnyReference = this.visitResult(ctx);
        const { trailers = [] } = reference;

        const undefinedParentWithTrailers = trailers.length > 0
            && reference.parentValue === undefined;

        if (undefinedParentWithTrailers) {
            this.throwWithContext(ctx, 
                'Undefined reference: ' + reference.name + '.' + trailers.join('.'));
        }

        return reference;
    }

    visitAtom_expr = (ctx: Atom_exprContext): void => {
        const executor = this.getExecutor();

        const firstId = ctx.ID(0)!;
        const atomId = firstId.getText();

        let currentReference: AnyReference;

        const idTrailers = [];
        if (ctx.ID().length > 1) {
            const idLength = ctx.ID().length;

            for (let i = 1; i < idLength; i++) {
                const tmpCtx = ctx.ID(i)!;
                idTrailers.push(tmpCtx.getText());
            }
        }

        // Check if it is hardcoded values, like the pin types.
        if (this.pinTypesList.indexOf(atomId) !== -1) {
            // Not sure if just returning the string is enough...
            currentReference = new AnyReference({
                found: true,
                value: atomId,
                type: ReferenceTypes.pinType,
            });
        } else {
            currentReference = executor.resolveVariable(
                this.executionStack, atomId, idTrailers);
        }

        if (currentReference.found && currentReference.type === 'instance' && idTrailers.length === 0) {
            const tmpComponent = currentReference.value as ClassComponent;

            // Copy the nets into the local net
            for (const [pinId, net] of tmpComponent.pinNets) {
                executor.scope.setNet(tmpComponent, pinId, net);
            }
        }

        // this.log2(`atomId: ${atomId} ${currentReference}`);

        if (ctx.parent instanceof ExpressionContext && !currentReference.found) {
            // If is an atom_expr and parent is just expression and no 
            // reference was found.
            this.throwWithContext(ctx, "Unknown symbol: " + atomId);
        }

        this.setResult(ctx, currentReference);
    }

    visitFunctionCallExpr = (ctx: FunctionCallExprContext): void => {
        const result = this.visitResult(
            ctx.function_call_expr()
        );
        this.setResult(ctx, result);
    }

    visitFunction_call_expr = (ctx: Function_call_exprContext): void => {
        const executor = this.getExecutor();
        const atomId = ctx.ID().getText();
        let passedNetNamespace = null; // Assumed empty by default

        const netNameSpaceExpr = ctx.net_namespace_expr();
        if (netNameSpaceExpr) {
            this.visit(netNameSpaceExpr);
            passedNetNamespace = this.getResult(netNameSpaceExpr);
        }

        let currentReference: AnyReference = executor.resolveVariable(
            this.executionStack, atomId);

        if (ctx.trailer_expr().length > 0) {
            // Resolve all elements in the trailer expression list

            if (!currentReference.found) {
                this.throwWithContext(ctx,
                    "Unknown function name: " + atomId);
            }

            currentReference.trailers = [];

            ctx.trailer_expr().forEach(item => {
                const itemValue = item.getText();
                if (item.OPEN_PAREN() && item.CLOSE_PAREN()) {
                    let parameters: CallableParameter[] = [];

                    const ctxParameters = item.parameters();
                    if (ctxParameters) {
                        this.visit(ctxParameters);
                        parameters = this.getResult(ctxParameters);
                    }

                    const useNetNamespace = this.getNetNamespace(
                        executor.netNamespace,
                        passedNetNamespace,
                    )

                    try {
                        const [, functionResult] =
                            executor.callFunction(
                                currentReference.name,
                                parameters,
                                this.executionStack,
                                useNetNamespace);

                        if (isReference(functionResult)){
                            currentReference = functionResult;
                        } else {
                            currentReference = new AnyReference({
                                found: true,
                                value: functionResult,
                                trailers: [],
                                type: (functionResult instanceof ClassComponent) ?
                                    ReferenceTypes.instance : ReferenceTypes.value,
                            });
                        }
                    } catch (err) {
                        this.throwWithContext(ctx, err);
                    }

                } else {
                    currentReference.trailers.push(itemValue);
                }
            });
        }

        this.setResult(ctx, currentReference);
    }

    visitValue_expr = (ctx: Value_exprContext): void => {
        const sign = ctx.Minus() ? -1 : 1;

        const ctxIntegerValue = ctx.INTEGER_VALUE();
        const ctxDecimalValue = ctx.DECIMAL_VALUE();
        const ctxNumericValue = ctx.NUMERIC_VALUE();
        const ctxBooleanValue = ctx.BOOLEAN_VALUE();
        const ctxStringValue = ctx.STRING_VALUE();
        const ctxPercentageValue = ctx.PERCENTAGE_VALUE();
        
        let result: ValueType | null = null;

        if (ctxIntegerValue || ctxDecimalValue || ctxNumericValue) {
            if (ctxIntegerValue) {
                result = resolveToNumericValue(
                    (new Big(ctxIntegerValue.getText())).mul(new Big(sign))
                );
            } else if (ctxDecimalValue) {
                result = resolveToNumericValue(
                    (new Big(ctxDecimalValue.getText())).mul(new Big(sign))
                );

            } else if (ctxNumericValue) {
                const textExtra = ctx.Minus() ? '-' : '';
                result = new NumericValue(textExtra + ctxNumericValue.getText());

            }
        } else {
            if (sign === -1) {
                this.throwWithContext(ctx, "Invalid value");
            }
        }

        if (ctxBooleanValue) {
            const stringValue = ctxBooleanValue.getText();
            if (stringValue === 'true') {
                result = true;
            } else if (stringValue === 'false') {
                result = false;
            }

        } else if (ctxStringValue) {
            result = this.prepareStringValue(ctxStringValue.getText());

        } else if (ctxPercentageValue) {
            result = new PercentageValue(ctxPercentageValue.getText());

        }

        this.setResult(ctx, result);
    }

    visitValueAtomExpr = (ctx: ValueAtomExprContext): void => {
        let value: ComplexType = null;

        const ctxValueExpr = ctx.value_expr();
        const ctxAtomExpr = ctx.atom_expr();

        if (ctxValueExpr) {
            this.visit(ctxValueExpr);
            value = this.getResult(ctxValueExpr);

        } else if (ctxAtomExpr) {
            this.visit(ctxAtomExpr);
            const reference = this.getResult(ctxAtomExpr);

            if (!reference.found) {
                value = new UndeclaredReference(reference);
            } else {
                // This is the returned component from the function call
                if (reference.type && reference.type === ReferenceTypes.pinType) {
                    value = reference;
                } else {
                    if (reference.trailers && reference.trailers.length > 0) {
                        value = reference;
                    } else {
                        value = reference.value;
                    }
                }
            }
        }

        this.setResult(ctx, value);
    }

    visitFunction_args_expr = (ctx: Function_args_exprContext): void => {
        const defaultValuesProvided = ctx.value_expr();
        // The last <defaultValuesProvided> IDs have default values
        const IDs = ctx.ID(); // Do in reverse

        const boundary = IDs.length - defaultValuesProvided.length;

        const result: FunctionDefinedParameter[] = IDs.map((id, index) => {
            const idText = id.getText();
            if (index >= boundary) {
                const tmpCtx = defaultValuesProvided[index - boundary];
                this.visit(tmpCtx);
                const defaultValue = this.getResult(tmpCtx);
                return [idText, tmpCtx.start!, defaultValue];
            } else {
            return [idText, id.getSymbol()];
            }
        });

        this.setResult(ctx, result);
    }

    visitParameters = (ctx: ParametersContext): void => {
        const dataExpressions = ctx.data_expr();
        const keywordAssignmentExpressions = ctx.keyword_assignment_expr();

        const returnList: CallableParameter[] = [];

        dataExpressions.forEach((item, index) => {
            const value = this.visitResult(item); 
            returnList.push(['position', index, value]);
        });

        keywordAssignmentExpressions.forEach((item) => {
            const [key, value] = this.visitResult(item);
            returnList.push(['keyword', key, value]);
        });

        this.setResult(ctx, returnList);
    }

    visitImport_expr = (ctx: Import_exprContext): void => {
        // Until a better solution is found, only allow import statements
        // to be parsed at the start of the script.
        throw new RuntimeExecutionError(
            "Cannot parse imports here", ctx);
    }

    visitFunction_return_expr = (ctx: Function_return_exprContext): void => {
        const executor = this.getExecutor();

        executor.log('return from function');

        const ctxDataExpr = ctx.data_expr();
        this.visit(ctxDataExpr)
        const returnValue = this.getResult(ctxDataExpr);

        executor.stopFurtherExpressions = true;
        executor.returnValue = returnValue;

        this.setResult(ctx, returnValue);
    }

    visitBreak_keyword = (ctx: Break_keywordContext): void => {
        // When the break keyword is encountered inside a branch, then leave the branch
        // without storing the final state. If used, the break should be
        // the last expression in the branch, any expressions after the break
        // will be skipped

        // this.getExecutor().breakBranch();
        // this.setResult(ctx, -1);

        const breakContext = this.getExecutor().getBreakContext();
        const currentResult = this.getResult(breakContext) ?? {};
        this.setResult(breakContext, {
            ...currentResult,
            breakSignal: true
        });
    }

    visitContinue_keyword = (ctx: Continue_keywordContext): void => {
        const breakContext = this.getExecutor().getBreakContext();
        const currentResult = this.getResult(breakContext) ?? {};
        this.setResult(breakContext, {
            ...currentResult,

            // continue is similar to break, except the loop is not 
            // completely stopped.
            breakSignal: true,
            continueSignal: true,
        });
    }

    visitArray_expr = (ctx: Array_exprContext): void => {
        const array = ctx.data_expr().map(item => {
            this.visit(item);
            return this.getResult(item);
        });

        this.setResult(ctx, array);
    }

    visitArrayExpr = (ctx: ArrayExprContext): void => {
        this.visit(ctx.array_expr());
        this.setResult(ctx, this.getResult(ctx.array_expr()));
    }

    protected setResult(ctx: ParserRuleContext, value: any): void {
        this.resultData.set(ctx, value);
    }

    protected getResult(ctx: ParserRuleContext): any {
        return this.resultData.get(ctx);
    }

    visitResult(ctx: ParserRuleContext): any {
        this.visit(ctx);
        return this.getResult(ctx);
    }

    protected async handleImportFile(name: string,
        throwErrors = true, ctx: ParserRuleContext | null = null): Promise<ImportFile> {

        name = name.trim();
        const importAlready = this.importedFiles.find(item => {
            return item.id === name;
        });

        if (importAlready) {
            return importAlready;
        }

        let hasError = false;
        let hasParseError = false;
        let pathExists = false;

        const tmpFilePath = this.environment.getRelativeToModule(name + ".cst");
        this.log('importing path:', tmpFilePath);

        let fileData: string | null = null;
        let filePathUsed: string | null = null;

        try {
            filePathUsed = tmpFilePath;
            fileData = await this.environment.readFile(tmpFilePath, { encoding: 'utf8' });
            pathExists = true;
        } catch (err) {
            pathExists = false;
        }

        if (!pathExists) {
            // if path does not exist, then search default libs path
            try {
                const tmpFilePath2 = this.environment.getRelativeToDefaultLibs(name + ".cst");
                filePathUsed = tmpFilePath2;

                fileData = await this.environment.readFile(tmpFilePath2, { encoding: 'utf8' });
                pathExists = true;
            } catch (err) {
                pathExists = false;
            }
        }

        try {
            if (pathExists) {
                this.log('done reading imported file data');

                const importResult = await this.onImportFile(this, 
                        filePathUsed, fileData!, this.onErrorHandler);

                hasError = importResult.hasError;
                hasParseError = importResult.hasParseError;
            }
        } catch (err) {
            if (ctx != null) {
                throw new RuntimeExecutionError("An error occurred while importing file", ctx);
            } else {
                this.log('An error occurred while importing file:', err.message);
            }
        }

        let errorMessage = null;
        
        if (throwErrors && (hasError || hasParseError || !pathExists)) {
            if (!pathExists) {
                errorMessage = `File does not exist: ${name} (${filePathUsed})`
            } else {
                errorMessage =  `Failed to import: ${name}`;
            }
        }

        if (errorMessage !== null && ctx){
            throw new RuntimeExecutionError(errorMessage, ctx);
        }

        // Keep track of already imported files
        const newImportedFile: ImportFile = {
            id: name.trim(),
            hasError,
            hasParseError,
            pathExists,
        }

        this.importedFiles.push(newImportedFile);

        return newImportedFile;
    }

    visitRoundedBracketsExpr = (ctx: RoundedBracketsExprContext):void => {
        const ctxDataExpr = ctx.data_expr();
        this.visit(ctxDataExpr);
        const innerResult = this.getResult(ctxDataExpr);
        this.setResult(ctx, innerResult);
    }

    protected setupDefinedParameters(
        funcDefinedParameters: FunctionDefinedParameter[], 
        passedInParameters: CallableParameter[], 
        executor: ExecutionContext): void {
        
        // Check if the arguments match up
        for (let i = 0; i < funcDefinedParameters.length; i++) {
            const tmpFuncArg = funcDefinedParameters[i];

            if (i < passedInParameters.length) {
                const tmpPassedInArgs = passedInParameters[i];
                const argValue = prepareValue(tmpPassedInArgs[2]);

                if (tmpPassedInArgs[0] === 'position') {
                    // If value is passed in as function parameter, then
                    // use it in the scope.
                    const variableName = tmpFuncArg[0];
                    executor.log(
                        'set variable in scope, var name: ',
                        variableName,
                    );

                    executor.scope.setVariable(
                        variableName,
                        argValue,
                    );

                    if (argValue instanceof ClassComponent) {
                        const component  = argValue;

                        // Add the component nets into the local scope
                        for(const [pinNumber, net] of component.pinNets){
                            executor.scope.setNet(component, pinNumber, net);
                        }
                    }
                } else if (tmpPassedInArgs[0] === 'keyword') {
                    const variableName = tmpPassedInArgs[1];
                    executor.log(
                        'set variable in scope, var name: ',
                        variableName
                    );

                    executor.scope.setVariable(
                        variableName,
                        argValue
                    );
                }

            } else if (tmpFuncArg.length === 3) {
                // Value was not provided to function, but a default 
                // value is provided.
                const variableName = tmpFuncArg[0];
                const defaultValue = tmpFuncArg[2];
                executor.log(
                    'set variable in scope, var name: ',
                    variableName,
                );
                executor.scope.setVariable(
                    variableName, defaultValue,
                );
            } else {
                throw `Invalid arguments got: ` + passedInParameters;
            }
        }
    }

    protected runExpressions(executor: ExecutionContext,
        expressions: ExpressionContext[] | Function_exprContext[]): ComplexType {

        let returnValue: ComplexType | null = null;

        // Track this context for a break signal
        const breakContext = executor.getBreakContext();

        // Execute the expressions within the context
        for (let i = 0; i < expressions.length; i++) {
            const expr = expressions[i];

            // The correct executor MUST be on the top/end of the stack!
            this.visit(expr);

            const { breakSignal = false } = this.getResult(breakContext) ?? {};
            if (breakSignal) {
                returnValue = executor.returnValue;
                break;
            }

            // If this flag is set, then do not parse anything further!
            if (executor.stopFurtherExpressions) {
                returnValue = executor.returnValue;
                break;
            }
        }

        return returnValue;
    }

    protected getNetNamespace(executorNetNamespace: string,
        passedNetNamespace: string | null): string {

        let result = executorNetNamespace;

        if (passedNetNamespace !== null && passedNetNamespace.length > 0) {
            // Either user specified '/' or '/_' to indicate the global
            // net namespace
            if (passedNetNamespace === '/' || passedNetNamespace === '_') {
                result = '';
            } else if (passedNetNamespace[0] === '+') {
                if (executorNetNamespace === '/') {
                    result = passedNetNamespace.slice(1)
                } else {
                    result = executorNetNamespace + passedNetNamespace.slice(2);
                }
            } else {
                result = passedNetNamespace;
            }

            result = result + '/';
        }

        return result;
    }

    protected setInstanceParam(object: ClassComponent, trailers: string[], value: any): void {
        const paramName = trailers[0];
        object.setParam(paramName, value);

        this.log2(
            `set instance ${object.instanceName} param ${paramName} to ${value}`);
    }

    protected getInstanceParam<T>(object: ClassComponent, trailers: string[]): T {
        const paramName = trailers[0];
        return object.getParam(paramName) as T;
    }

    protected enterNewChildContext(executionStack: ExecutionContext[],
        parentContext: ExecutionContext,
        executionContextName: string,
        options: CFunctionOptions,
        funcDefinedParameters: FunctionDefinedParameter[],
        passedInParameters: CallableParameter[]
    ): ExecutionContext {
        const { netNamespace = "" } = options;

        // Create a new execution context, so that the commands are executed only
        // within this context. Components and nets will be local to this context for now.
        const currentExecutionContext =
            executionStack[executionStack.length - 1];
        const executionLevel = currentExecutionContext.executionLevel;

        const executionContextNamespace = currentExecutionContext.namespace
            + executionContextName + ".";

        const newExecutor = new ExecutionContext(
            executionContextName,
            executionContextNamespace,
            netNamespace,
            executionLevel + 1,
            this.getExecutor().scope.indentLevel + 1,
            currentExecutionContext.silent,
            currentExecutionContext.logger,
            currentExecutionContext.warnings,
            parentContext
        );

        // Add the execution context to the end of the execution stack
        executionStack.push(newExecutor);

        // Setup the params in the execution scope if there 
        // are any function parameters

        this.setupDefinedParameters(
            funcDefinedParameters,
            passedInParameters,
            newExecutor
        );

        return newExecutor;
    }

    protected prepareStringValue(value: string): string {
        return value.slice(1, value.length - 1);
    }

    protected throwWithContext(context: ParserRuleContext, messageOrError: string | BaseError): void {
        throwWithContext(context, messageOrError);
    }

    protected validateType(value: any,
        context: ParserRuleContext,
        validateFunction: (value: any) => boolean,
        expectedType: string): boolean {

        if (value === undefined) {
            return false;
        }

        const result = validateFunction(value);
        if (!result) {
            throw new RuntimeExecutionError(`Invalid ${expectedType}`, context);
        }

        return result;
    }

    protected validateString(value: any, context: ParserRuleContext): void {
        this.validateType(value, context, (val) => {
            return typeof val === 'string';
        }, 'string');
    }

    protected validateBoolean(value: any, context: ParserRuleContext): void {
        this.validateType(value, context, (val) => {
            return typeof val === 'boolean';
        }, 'boolean');
    }

    protected validateNumeric(value: any, context: ParserRuleContext): void {
        this.validateType(value, context, (val) => {
            return (val instanceof NumericValue);
        }, 'numeric value');
    }

}

export type OnErrorHandler = 
    (message: string, context: ParserRuleContext, e?: any) => void;

type ImportFile = {
    id: string,
    hasError: boolean,
    hasParseError: boolean,
    pathExists: boolean
}