/*
 * Copyright 2023 Liu Weihao
 * 
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Big } from 'big.js';

import {
    ArrayExprContext, Assignment_exprContext, Callable_exprContext,
    CallableExprContext, ExpressionContext, Flow_expressionsContext,
    Function_args_exprContext, Function_exprContext, Function_return_exprContext, Import_exprContext,
    Import_simpleContext, Import_specific_or_allContext, Keyword_assignment_exprContext,
    ParametersContext, RoundedBracketsExprContext, ScriptContext,
    TrailerContext,
    Value_exprContext, 
    ValueExprContext} from "./antlr/CircuitScriptParser.js";
import { CircuitScriptParserVisitor } from "./antlr/CircuitScriptParserVisitor.js";
import { ExecutionContext } from "./execute.js";
import { Logger } from "./logger.js";
import { ClassComponent } from "./objects/ClassComponent.js";
import { Net } from "./objects/Net.js";
import { NumberOperator, NumberOperatorType, NumericValue, PercentageValue } from "./objects/ParamDefinition.js";
import { CallableParameter, ComplexType, 
    Direction, 
    FunctionDefinedParameter, AnyReference, UndeclaredReference, 
    ValueType,
    ImportedLibrary,
    NewContextOptions,
    ImportFunctionHandling as ImportFunctionHandling} from "./objects/types.js";
import { CommonTokenStream, ParserRuleContext } from 'antlr4ng';
import { BaseNamespace, ComponentTypes, DoubleDelimiter1, GlobalDocumentName, PinTypesList, ReferenceTypes, TrailerArrayIndex } from './globals.js';
import { ExecutionWarning, isReference, unwrapValue as unwrapValue } from "./utils.js";
import { linkBuiltInMethods } from './builtinMethods.js';
import { BaseError, resolveToNumericValue, RuntimeExecutionError, throwWithContext } from './utils.js';
import { ExecutionScope, SequenceAction } from './objects/ExecutionScope.js';
import { NodeScriptEnvironment } from "./environment.js";
import { PinId } from './objects/PinDefinition.js';
import { computeContentHash } from './cache/hash.js';
import { readCache, writeCache } from './cache/storage.js';
import { serializeLibraryScope } from './cache/serializer.js';
import { deserializeLibraryScope } from './cache/deserializer.js';
import { resolveAllImportFilepaths } from './importResolver.js';

export class BaseVisitor extends CircuitScriptParserVisitor<ComplexType | AnyReference | any> {
    // See class CircuitScriptVisitor (generated by antlr4) to find method names

    // Contains the methods here, so that it is function based instead
    // of just lambdas/callbacks...

    startingContext: ExecutionContext;
    executionStack: ExecutionContext[];
    
    // Used to determine the current file being parsed.
    filePathStack: string[] = [];

    // If true, then do not print out anything
    silent = false;

    logger: Logger;

    printStream: string[] = [];
    printToConsole = true;
    
    allowParseImports = false;

    acceptedDirections = [Direction.Up, Direction.Down, 
        Direction.Right, Direction.Left];
    
    // Store results before or after a visitor method is called.
    protected resultData = new Map<ParserRuleContext, any>;

    // Mapping of contexts to ClassComponent instances. This is used for 
    // refdes annotation comments and only graph related (at, to) rule contexts
    // are tracked.
    protected componentCtxLinks = new Map<ParserRuleContext, ClassComponent>;

    onErrorHandler: OnErrorHandler | null = null;
    environment: NodeScriptEnvironment;

    protected importedFiles:ImportLibraryFile[] = [];

    protected warnings:ExecutionWarning[] = [];

    // Maps filenames to file contents.
    loadedFiles: Map<string, string> = new Map();
    
    enableCacheImports = true;

    enableCachedImportsRead = false || this.enableCacheImports;
    enableCachedImportsWrite = false || this.enableCacheImports;

    // Callback to set behaviour when file is imported
    onImportFile = (visitor: BaseVisitor, filePath:string, fileData: string, 
        onErrorHandler: OnErrorHandler, fileLineOffset: number): ImportFileResult => {
        throw "Import file not implemented"
    }

    // Stores refdes file annotation keys to the refdes output
    refdesFileAnnotations = new Map<string, string>();

    constructor(silent = false, 
        onErrorHandler: OnErrorHandler | null = null,
        environment: NodeScriptEnvironment) {
        
        super();
        this.silent = silent;
        this.logger = new Logger();
        this.onErrorHandler = onErrorHandler;
        this.environment = environment;

        this.startingContext = new ExecutionContext(
            DoubleDelimiter1,
            BaseNamespace,
            '/',
            0, 0, silent, 
            this.logger, 
            this.warnings,
            null);

        const scope = this.startingContext.scope;

        // Start the sequence list with the cursor positioned at
        // the root node.
        scope.sequence.push([
            SequenceAction.At, scope.componentRoot!, scope.currentPin!
        ]);

        // Add the document global object, this is used to set the page size
        scope.setVariable(GlobalDocumentName, {
            'bom': {},  // Store bom configuration
        });
        
        this.setupBuiltInFunctions(this.startingContext);
            
        this.executionStack = [this.startingContext];
        this.startingContext.resolveNet = 
            this.createNetResolver(this.executionStack);

        this.startingContext.resolveComponentPinNet = 
            this.createComponentPinNetResolver(this.executionStack);

        this.silent = silent;
    }

    getExecutor(): ExecutionContext {
        return this.executionStack[this.executionStack.length - 1];
    }

    getScope(): ExecutionScope {
        return this.getExecutor().scope;
    }

    getRootExecutor(): ExecutionContext {
        return this.executionStack[0];
    }

    protected setupBuiltInFunctions(context: ExecutionContext): void {
        linkBuiltInMethods(context, this);
    }

    createNetResolver(executionStack: ExecutionContext[]): 
        (netName: string, netNamespace: string) => {found: boolean, net?: Net} {
        const resolveNet = (netName: string, netNamespace: string): 
            {found: boolean, net?: Net} => {
            // netNamespace is the current netNamespace where the net name is 
            // searching from.

            this.log('find net', netNamespace, netName);
            const reversed = [...executionStack].reverse();

            for (let i = 0; i < reversed.length; i++) {
                const context = reversed[i];
                const net = context.scope.getNetWithName(netName);

                if (net !== null && net.namespace === netNamespace) {
                    return {
                        found: true,
                        net,
                    }
                }
            }

            return {
                found: false
            }
        }

        return resolveNet;
    }
    
    createComponentPinNetResolver(executionStack: ExecutionContext[]):
        (component: ClassComponent, pin: PinId) => Net | null {

        return (component: ClassComponent, pin: PinId): Net | null => {
            const reversed = [...executionStack].reverse();

            for (let i = 0; i < reversed.length; i++) {
                const context = reversed[i];
                const net = context.scope.getNet(component, pin);
                if (net !== null) {
                    return net;
                }
            }

            return null;
        };
    }

    log(...params: any[]): void {
        const indentLevel = this.getScope().scopeLevel;

        const indentOutput = ''.padStart(indentLevel * 4, '    ');
        const indentLevelText = indentLevel.toString().padStart(3, ' ');

        const args = ['[' + indentLevelText + ']', indentOutput, ...params];
        
        this.logger.add(args.join(' '));

        if (!this.silent) {
            console.log.apply(null, args);
        }
    }

    /**
     * Add to the executor log
     */
    log2(message: string): void {
        this.getExecutor().log(message);
    }

    async resolveImportsAndLoad(inputPath: string, scriptData: string): Promise<void> {
        this.log('resolve and load imports');

        const importedFiles = await resolveAllImportFilepaths(inputPath,
            scriptData, this.environment);
        this.log('resolved all referenced imports');

        // Load all the files
        const loadedFiles = new Map<string, string>();
        for (const importFilePath of importedFiles) {
            this.log(`reading file: ${importFilePath}`);
            const importFileData = await this.environment.readFile(importFilePath);
            loadedFiles.set(importFilePath, importFileData);
        }

        // Check if the main refdes file exists
        if (this.filePathStack.length > 0) {
            const mainRefdesFile = this.getPathRefdesFile(this.filePathStack[0]);
            const fileExists = await this.environment.exists(mainRefdesFile);
            if (fileExists) {
                this.log('.refdes.json file exists, reading it');
                const mainRefdesFileData = await this.environment.readFile(mainRefdesFile);
                loadedFiles.set(mainRefdesFile, mainRefdesFileData);
            }
        }

        this.loadedFiles = loadedFiles;
    }

    visitScript = (ctx: ScriptContext): void => {
        this.log('===', 'start', '===');

        this.allowParseImports = true;

        // Parse all import statements at the start
        for (const ctxImport of ctx.import_expr()) {
            this.visit(ctxImport);
        }

        this.allowParseImports = false;

        const result = this.runExpressions(this.getExecutor(), ctx.expression());
        this.setResult(ctx, result);

        // If there are open blocks, then close them
        this.getExecutor().closeOpenPathBlocks();

        this.log('===', 'end', '===');
    }

    private importCommon(ctx: Import_simpleContext | Import_specific_or_allContext,
        handling: ImportFunctionHandling): void {
        const specificImports: string[] = [];
        if (ctx instanceof Import_specific_or_allContext) {
            const tmpSpecificImports = ctx._funcNames.map(item => {
                return item.text!;
            });

            specificImports.push(...tmpSpecificImports);
        }

        const id = ctx._libraryName!.text!.slice(1, -1);
        const importedFile = this.handleImportFile(id, handling, true, ctx, specificImports);

        const ctxImportAnnotation = ctx.annotation_comment_expr();
        if (ctxImportAnnotation) {
            const textValue = ctxImportAnnotation.getText().replace('#=', '');
            const { importedLibrary } = importedFile;
            if (textValue === 'annotate') {
                importedLibrary.enableRefdesAnnotation = true;
            } else if (textValue === 'annotate-external') {
                importedLibrary.enableRefdesAnnotationFile = true;
            }
        }
    }

    visitImport_simple = (ctx: Import_simpleContext): void => {
        this.importCommon(ctx, ImportFunctionHandling.AllWithNamespace);
    }

    visitImport_specific_or_all = (ctx: Import_specific_or_allContext): void => {
        let importType = ImportFunctionHandling.SpecificMergeIntoNamespace;
        if (ctx._all){
            importType = ImportFunctionHandling.AllMergeIntoNamespace
        }

        this.importCommon(ctx, importType);
    }

    visitCallableExpr = (ctx: CallableExprContext): void => {
        this.passResult(ctx, ctx.callable_expr());
    }

    visitCallable_expr = (ctx: Callable_exprContext): void => {
        const ctxParams = this.getResult(ctx);

        // If keepReference is true, then keep the reference that is returned
        // after a function call. This reference may be used in the LHS of
        // an assignment.
        const { keepReference = false } = ctxParams ?? {};

        const executor = this.getExecutor();

        let passedNetNamespace = null;
        const netNameSpaceExpr = ctx.net_namespace_expr();
        if (netNameSpaceExpr) {
            passedNetNamespace = this.visitResult(netNameSpaceExpr);
        }

        const firstId = ctx.ID(0)!;
        const atomId = firstId.getText();
        
        let currentReference: AnyReference;

        // Check if it is hardcoded values, like the pin types.
        if (PinTypesList.indexOf(atomId) !== -1 && ctx.trailer().length === 0) {
            // Not sure if just returning the string is enough...
            currentReference = new AnyReference({
                found: true,
                value: atomId,
                type: ReferenceTypes.pinType,
            });
        } else {
            this.log('resolve variable ctx: ' + ctx.getText(), 'atomId', atomId);
            currentReference = executor.resolveVariable(
                this.executionStack, atomId);
            this.log('reference:', currentReference.name, 'found:', currentReference.found);
        }

        if (currentReference !== undefined && currentReference.found) {
            ctx.trailer().forEach(ctxTrailer => {
                this.setResult(ctxTrailer, {
                    reference: currentReference,
                    netNamespace: passedNetNamespace
                });
                currentReference = this.visitResult(ctxTrailer);
            });
        }

        let resultValue = currentReference;
        if (!keepReference) {
            // Only if is pin type, then keep the reference.
            if (currentReference.type !== ReferenceTypes.pinType) {
                resultValue = unwrapValue(resultValue);
            }
        }

        this.setResult(ctx, resultValue);
        this.log2('atom resolved: ' + ctx.getText() + ' -> ' + currentReference);
    }

    visitTrailer = (ctx: TrailerContext): void => {
        // There should be some reference already set
        const { reference, netNamespace } = this.getResult(ctx) as { reference: AnyReference, netNamespace: string | null };

        const ctxLParam = ctx.LParen();         // Function call access
        const ctxID = ctx.ID();                 // Dot access expression
        const ctxDataExpr = ctx.data_expr();    // Array access

        const useValue = reference.value;
        let nextReference!: AnyReference;

        if (ctxID) {
            // Extend the property in reference
            reference.trailers.push(ctxID.getText());

            const useRootValue = reference.rootValue ?? reference.value;
            const useTrailerIndex = reference.trailerIndex ?? 0;

            nextReference = this.getExecutor().resolveTrailers(
                reference.type,
                useRootValue,
                reference.trailers
            );

            nextReference.name =
                [reference.name,
                ...reference.trailers.slice(useTrailerIndex)].join('.');

        } else if (ctxDataExpr) {
            const arrayIndex = this.visitResult(ctxDataExpr);
            if (arrayIndex instanceof NumericValue) {
                const arrayIndexValue = arrayIndex.toNumber();
                const foundValue = useValue[arrayIndexValue];

                const refType = foundValue instanceof ClassComponent
                    ? ReferenceTypes.instance : ReferenceTypes.variable;

                nextReference = new AnyReference({
                    found: true,
                    type: refType,
                    value: foundValue,
                    trailers: [[TrailerArrayIndex, arrayIndexValue]],
                    rootValue: useValue
                });
            }

        } else if (ctxLParam) {
            nextReference = this.handleFunctionCall(reference, netNamespace, ctx);
        }

        this.setResult(ctx, nextReference);
    }

    visitAssignment_expr = (ctx: Assignment_exprContext): void => {
        if (ctx.Assign()) {
            // Simple assignment: lhs = rhs
            const lhsCtx = ctx.callable_expr();
            this.setResult(lhsCtx, {keepReference: true});
            const leftSideReference = this.visitResult(lhsCtx);

            const rhsCtx = ctx.data_expr();
            const rhsCtxResult = this.visitResult(rhsCtx);

            if (isReference(rhsCtxResult) && !rhsCtxResult.found) {
                // The value does not exists
                this.throwWithContext(rhsCtx, rhsCtx.getText() + ' is not defined');
            }

            const rhsValue = unwrapValue(rhsCtxResult);
            const { trailers = [] } = leftSideReference;
            const sequenceParts: (string | any)[] = [];

            if (trailers.length === 0) {
                // No trailers, directly assign the reference name
                this.getScope().setVariable(leftSideReference.name!, rhsValue);

                let itemType = '';
                if (rhsValue instanceof ClassComponent) {
                    itemType = ReferenceTypes.instance;
                    this.log2(
                        `assigned '${leftSideReference.name}' to ClassComponent`,
                    );
                } else {
                    itemType = ReferenceTypes.variable;
                    this.getScope().setVariable(leftSideReference.name!, rhsValue);
                    this.log2(`assigned variable ${leftSideReference.name} to ${rhsValue}`);
                }

                sequenceParts.push(...[itemType, leftSideReference.name, rhsValue]);
            } else {
                if (leftSideReference.rootValue instanceof ClassComponent) {
                    this.setInstanceParam(leftSideReference.rootValue, trailers, rhsValue);
                    this.log2(`assigned component param ${leftSideReference.rootValue} trailers: ${trailers} value: ${rhsValue}`);

                    sequenceParts.push(...['instance', [leftSideReference.rootValue, trailers], rhsValue]);

                    if (leftSideReference.rootValue.typeProp === ComponentTypes.net) {
                        // if a net component, there is onl 1 pin
                        const net = this.getScope().getNet(
                            leftSideReference.rootValue, new PinId(1));
                        if (net) {
                            const trailerValue = trailers.join(".");
                            net.params.set(trailerValue, rhsValue);
                        }
                    }

                } else if (leftSideReference.rootValue instanceof Object) {
                    // TODO: instanceof use AnyReference?

                    // Array access assignment
                    if (Array.isArray(trailers[0]) && trailers[0][0] === TrailerArrayIndex) {
                        if (Array.isArray(leftSideReference.rootValue)) {
                            const arrayIndexValue = trailers[0][1];
                            leftSideReference.rootValue[arrayIndexValue] = rhsValue;

                            this.log2(`assigned array index ${leftSideReference.rootValue} index: ${arrayIndexValue} value: ${rhsValue}`);

                        } else {
                            this.throwWithContext(lhsCtx, "Invalid array");
                        }
                    } else {
                        // Object access assignment

                        // Expand the object first
                        let expandedValue = leftSideReference.rootValue;

                        // Skip the last trailer
                        trailers.slice(0, -1).forEach(trailer => {
                            expandedValue = expandedValue[trailer];
                        });
                        const lastTrailer = trailers.slice(-1)[0];

                        expandedValue[lastTrailer] = rhsValue;
                        this.log2(`assigned object ${leftSideReference.rootValue} trailers: ${trailers} value: ${rhsValue}`)
                    }

                    sequenceParts.push(...['variable', [leftSideReference.rootValue, trailers], rhsValue]);
                }
            }

            if (sequenceParts.length > 0) {
                this.getScope().sequence.push([
                    SequenceAction.Assign, ...sequenceParts
                ]);
            }

            this.setResult(ctx, rhsValue);
        } else {
            // Compound assignment: lhs += rhs, lhs -= rhs, etc.
            const ctxCallable = ctx.callable_expr();
            this.setResult(ctxCallable, {keepReference: true});
            const reference = this.visitResult(ctx.callable_expr());

            const value = this.visitResult(ctx.data_expr());

            if (!reference.found) {
                this.throwWithContext(ctx, 'Undefined reference: ' + reference.name);
            }

            const trailers = reference.trailers ?? [];

            let currentValue: NumberOperatorType | number | null = null;

            if (trailers.length === 0) {
                currentValue = this.getExecutor().scope.variables.get(reference.name) as number;
            } else {
                if (reference.value instanceof ClassComponent) {
                    currentValue = this.getInstanceParam(reference.value, trailers);
                } else if (reference.value instanceof Object) {
                    currentValue = reference.value[trailers.join('.')];
                }
            }

            if (currentValue === null) {
                this.throwWithContext(ctx,
                    'Operator assignment failed: could not get value');
            }

            let newValue: number | NumberOperatorType = 0;

            const operator = new NumberOperator();
            if (ctx.AdditionAssign()) {
                newValue = operator.addition(
                    currentValue as NumberOperatorType, value);
            } else if (ctx.MinusAssign()) {
                newValue = operator.subtraction(
                    currentValue as NumberOperatorType, value);
            } else if (ctx.MultiplyAssign()) {
                newValue = operator.multiply(
                    currentValue as NumberOperatorType, value);
            } else if (ctx.DivideAssign()) {
                newValue = operator.divide(
                    currentValue as NumberOperatorType, value);
            } else if (ctx.ModulusAssign()) {
                newValue = operator.modulus(
                    currentValue as NumberOperatorType, value);
            } else {
                this.throwWithContext(ctx,
                    'Operator assignment failed: could not perform operator');
            }

            // Reassign back to value
            if (trailers.length === 0) {
                this.getExecutor().scope.setVariable(reference.name, newValue);
            } else {
                if (reference.value instanceof ClassComponent) {
                    this.setInstanceParam(reference.value, trailers, newValue);
                } else if (reference.value instanceof Object) {
                    reference.value[trailers.join('.')] = newValue;
                }
            }

            this.setResult(ctx, newValue);
        }
    }

    private getReference(ctx: Atom_exprContext): AnyReference {
        const atomStr = ctx.getText();

        // Do not allow the atom to have any parentheses in the assignment
        if (atomStr.indexOf('(') !== -1 || atomStr.indexOf(')') !== -1) {
            this.throwWithContext(ctx, "Invalid assignment expression!");
        }

        const reference: AnyReference = this.visitResult(ctx);
        const { trailers = [] } = reference;

        const undefinedParentWithTrailers = trailers.length > 0
            && reference.rootValue === undefined;

        if (undefinedParentWithTrailers) {
            this.throwWithContext(ctx, 
                'Undefined reference: ' + reference.name + '.' + trailers.join('.'));
        }

        return reference;
    }

    visitTrailer_expr2 = (ctx: Trailer_expr2Context): void => {
        // There should be some reference already set
        const reference = this.getResult(ctx) as AnyReference;

        const ctxID = ctx.ID();
        const ctxDataExpr = ctx.data_expr();
        
        const useValue = reference.value;

        let nextReference!: AnyReference;

        if (ctxID){
            // Extend the property in reference
            reference.trailers.push(ctxID.getText());

            const useRootValue = reference.rootValue ?? reference.value;
            const useTrailerIndex = reference.trailerIndex ?? 0;

            nextReference = this.getExecutor().resolveTrailers(
                reference.type, 
                useRootValue,
                reference.trailers
            );

            nextReference.name = 
                [reference.name, 
                    ...reference.trailers.slice(useTrailerIndex)].join('.');

        } else if (ctxDataExpr) {
            const arrayIndex = this.visitResult(ctxDataExpr);
            if (arrayIndex instanceof NumericValue){
                const arrayIndexValue = arrayIndex.toNumber();
                const foundValue = useValue[arrayIndexValue]; 

                const refType = foundValue instanceof ClassComponent 
                    ? ReferenceTypes.instance : ReferenceTypes.variable;

                nextReference = new AnyReference({
                    found: true,
                    type: refType,
                    value: foundValue,
                    trailers: [[TrailerArrayIndex, arrayIndexValue]],
                    rootValue: useValue
                });
            }
        }
        
        this.setResult(ctx, nextReference);
    }

    visitAtom_expr = (ctx: Atom_exprContext): void => {
        const executor = this.getExecutor();

        const firstId = ctx.ID(0)!;
        const atomId = firstId.getText();
        
        let currentReference: AnyReference;

        // Check if it is hardcoded values, like the pin types.
        if (PinTypesList.indexOf(atomId) !== -1) {
            // Not sure if just returning the string is enough...
            currentReference = new AnyReference({
                found: true,
                value: atomId,
                type: ReferenceTypes.pinType,
            });
        } else {
            this.log('resolve variable ctx: ' + ctx.getText(), 'atomId', atomId);
            currentReference = executor.resolveVariable(
                this.executionStack, atomId);
            this.log('reference:', currentReference.name, 'found:', currentReference.found);
        }

        if (currentReference !== undefined && currentReference.found) {
            ctx.trailer_expr2().forEach(ctxTrailer => {
                this.setResult(ctxTrailer, currentReference);
                currentReference = this.visitResult(ctxTrailer);
            });
        }
        
        this.setResult(ctx, currentReference);
        this.log2('atom resolved: ' + ctx.getText() + ' -> ' + currentReference);
    }

     /**
     * Executes the function and returns a reference to the result of the
     * function. A reference is always returned.
     */
    private handleFunctionCall(currentReference: AnyReference, 
        passedNetNamespace: string| null, ctx: TrailerContext): AnyReference {
        
        const executor = this.getExecutor();
                
        let parameters: CallableParameter[] = [];

        const ctxParameters = ctx.parameters();
        if (ctxParameters) {
            parameters = this.visitResult(ctxParameters);
        }

        const useNetNamespace = this.getNetNamespace(
            executor.netNamespace,
            passedNetNamespace,
        );

        try {
            const isLibraryFunction = currentReference.rootValue 
                && currentReference.rootValue instanceof ImportedLibrary;

            if (isLibraryFunction){
                this.log('create new library context');

                // Restore the library context
                const importedLibrary = currentReference.rootValue as ImportedLibrary;
                const {context: importedLibraryContext} = importedLibrary;

                // When executing library function, update the
                // active filepath.
                this.enterFile(importedLibrary.libraryFilePath);

                const newExecutor = this.handleEnterContext(
                    this.getExecutor(),
                    this.executionStack,
                    importedLibraryContext.name,
                    ctx,
                    {
                        netNamespace: executor.netNamespace,
                        namespace: importedLibrary.libraryNamespace
                    }, [], [],
                    false
                );

                this.log('copy library context scope');
                importedLibraryContext.scope.copyTo(newExecutor.scope);
            }

            const [, functionResult] =
                executor.callFunction(
                    currentReference,
                    parameters,
                    this.executionStack,
                    useNetNamespace);

            if (isLibraryFunction){
                this.log('pop library context scope');
                this.handlePopContext(
                    this.getExecutor(),
                    this.executionStack,
                    "",
                    false
                );

                this.exitFile();
            }

            if (isReference(functionResult)){
                currentReference = functionResult;
            } else {
                currentReference = new AnyReference({
                    found: true,
                    value: functionResult,
                    trailers: [],
                    type: (functionResult instanceof ClassComponent) ?
                        ReferenceTypes.instance : ReferenceTypes.value,
                });
            }
        } catch (err) {
            this.throwWithContext(ctx, err);
        }

        return currentReference;
    }

    /**
     * Reusable method to enter a new child context.
     * @param executor 
     * @param executionStack 
     * @param contextName 
     * @param ctx 
     * @param options 
     * @param funcDefinedParameters 
     * @param passedInParameters 
     * @param isBreakContext If true, then the new context is a break context (can be disrupted by break/return keyword). This is also used to determine indexing for refdes annotations.
     * @returns 
     */
    protected handleEnterContext(executor: ExecutionContext,
        executionStack: ExecutionContext[],
        contextName: string,
        ctx: ParserRuleContext,
        options: NewContextOptions,
        funcDefinedParameters: FunctionDefinedParameter[],
        passedInParameters: CallableParameter[],
        isBreakContext = true
    ): ExecutionContext {

        if (isBreakContext) {
            const parentBreakContext = executor.getParentBreakContext();
            executor.addBreakContext(ctx);

            let useIndex = -1;
            if (parentBreakContext === null) {
                // If not in a break context, then use the function call index 
                // within the current scope
                useIndex = options.functionCallIndex;
            } else {
                // Otherwise use the function call index within the 
                // parent context
                const parentEntry = executor.indexedStack.get(parentBreakContext)!;
                const { funcCallIndex } = parentEntry;
                if (!funcCallIndex.has(ctx)) {
                    funcCallIndex.set(ctx, 0);
                    useIndex = 0;
                } else {
                    useIndex = funcCallIndex.get(ctx)! + 1;
                    funcCallIndex.set(ctx, useIndex);
                }
            }

            // Use the function call index within the current scope
            executor.setBreakContextIndex(useIndex);
        }

        return this.enterNewChildContext(
            executionStack,
            executor,
            contextName,
            options,
            funcDefinedParameters,
            passedInParameters
        );
    }

    /**
     * Reusable method to handle leaving/closing a new child context.
     * @param executor 
     * @param executionStack 
     * @param namespaceExtension 
     * @param isBreakContext See definition from handleEnterContext
     * @returns 
     */
    protected handlePopContext(executor: ExecutionContext,
        executionStack: ExecutionContext[],
        namespaceExtension: string,
        isBreakContext = true): ExecutionContext {

        const poppedContext = executionStack.pop()!;

        // Merge what ever was created in the scope with the outer scope
        const nextLastExecution = executionStack[executionStack.length - 1];
        const mergedComponents = nextLastExecution.mergeScope(
            poppedContext.scope,
            namespaceExtension
        );

        if (isBreakContext) {
            const scope = this.getScope();
            const indexedStack: [ParserRuleContext, number][] = [];
            if (scope.breakStack.length > 0) {
                const executor = this.getExecutor();
                scope.breakStack.forEach(stackCtx => {
                    const entry = executor.indexedStack.get(stackCtx)!;
                    const { index } = entry;
                    indexedStack.push([stackCtx, index]);
                });

                mergedComponents.forEach(component => {
                    // Need to update all the context links with the current breakStack
                    component.ctxReferences.forEach(ref => {
                        ref.indexedStack = [...indexedStack, ...ref.indexedStack];
                    });
                });
            }

            executor.popBreakContext();
        }

        return poppedContext;
    }

    visitValue_expr = (ctx: Value_exprContext): void => {
        const sign = ctx.Minus() ? -1 : 1;
        
        const ctxIntegerValue = ctx.INTEGER_VALUE();
        const ctxDecimalValue = ctx.DECIMAL_VALUE();
        const ctxNumericValue = ctx.NUMERIC_VALUE();
        const ctxBooleanValue = ctx.BOOLEAN_VALUE();
        const ctxStringValue = ctx.STRING_VALUE();
        const ctxPercentageValue = ctx.PERCENTAGE_VALUE();
        
        let result: ValueType | null = null;

        if (ctxIntegerValue || ctxDecimalValue || ctxNumericValue) {
            if (ctxIntegerValue) {
                result = resolveToNumericValue(
                    (new Big(ctxIntegerValue.getText())).mul(new Big(sign))
                );
            } else if (ctxDecimalValue) {
                result = resolveToNumericValue(
                    (new Big(ctxDecimalValue.getText())).mul(new Big(sign))
                );

            } else if (ctxNumericValue) {
                const textExtra = ctx.Minus() ? '-' : '';
                result = new NumericValue(textExtra + ctxNumericValue.getText());

            }
        } else {
            if (sign === -1) {
                this.throwWithContext(ctx, "Invalid value");
            }
        }

        if (ctxBooleanValue) {
            const stringValue = ctxBooleanValue.getText();
            if (stringValue === 'true') {
                result = true;
            } else if (stringValue === 'false') {
                result = false;
            }

        } else if (ctxStringValue) {
            result = this.prepareStringValue(ctxStringValue.getText());

        } else if (ctxPercentageValue) {
            result = new PercentageValue(ctxPercentageValue.getText());

        }

        this.setResult(ctx, result);
    }

    visitValueExpr = (ctx: ValueExprContext): void => {
        this.passResult(ctx, ctx.value_expr());
    }

    visitAtomExpr = (ctx: AtomExprContext): void => {
        let value: ComplexType = null;
        const reference = this.visitResult(ctx.atom_expr());

        if (!reference.found) {
            value = new UndeclaredReference(reference);
        } else {
            // This is the returned component from the function call
            if (reference.type && reference.type === ReferenceTypes.pinType) {
                value = reference;
            } else {
                if ((reference.trailers && reference.trailers.length > 0) 
                    || reference.type === ReferenceTypes.function) {
                    
                    value = reference;
                } else {
                    value = reference.value;
                }
            }
        }

        this.setResult(ctx, value);
    }

    visitFunction_args_expr = (ctx: Function_args_exprContext): void => {
        const defaultValuesProvided = ctx.value_expr();
        // The last <defaultValuesProvided> IDs have default values
        const IDs = ctx.ID(); // Do in reverse

        const boundary = IDs.length - defaultValuesProvided.length;

        const result: FunctionDefinedParameter[] = IDs.map((id, index) => {
            const idText = id.getText();
            if (index >= boundary) {
                const tmpCtx = defaultValuesProvided[index - boundary];
                this.visit(tmpCtx);
                const defaultValue = this.getResult(tmpCtx);
                return [idText, tmpCtx.start!, defaultValue];
            } else {
            return [idText, id.getSymbol()];
            }
        });

        this.setResult(ctx, result);
    }

    visitKeyword_assignment_expr = (ctx: Keyword_assignment_exprContext): void => {
        const id = ctx.ID().getText();
        const value = this.visitResult(ctx.data_expr());
        
        this.setResult(ctx, [id, value]);
    }

    visitParameters = (ctx: ParametersContext): void => {
        const dataExpressions = ctx.data_expr();
        const keywordAssignmentExpressions = ctx.keyword_assignment_expr();

        const returnList: CallableParameter[] = [];

        // Values are wrapped if they are a reference, and this method
        // assumes that the values are to be used.
        dataExpressions.forEach((item, index) => {
            const value = this.visitResult(item);
            returnList.push(['position', index, unwrapValue(value)]);
        });

        keywordAssignmentExpressions.forEach((item) => {
            const [key, value] = this.visitResult(item);
            returnList.push(['keyword', key, unwrapValue(value)]);
        });

        this.setResult(ctx, returnList);
    }

    visitImport_expr = (ctx: Import_exprContext): void => {
        // Until a better solution is found, only allow import statements
        // to be parsed at the start of the script.
        throw new RuntimeExecutionError(
            "Cannot parse imports here", ctx);
    }

    visitFunction_return_expr = (ctx: Function_return_exprContext): void => {
        const executor = this.getExecutor();

        executor.log('return from function');
        const returnValue = this.visitResult(ctx.data_expr());

        executor.stopFurtherExpressions = true;
        executor.returnValue = returnValue;

        this.setResult(ctx, returnValue);
    }

    visitFlow_expressions = (ctx: Flow_expressionsContext): void => {
        if (ctx.if_expr()) {
            this.visit(ctx.if_expr()!);
        } else if (ctx.while_expr()) {
            this.visit(ctx.while_expr()!);
        } else if (ctx.for_expr()) {
            this.visit(ctx.for_expr()!);
        } else if (ctx.Break() || ctx.Continue()) {
            // When the `break` keyword is encountered inside a branch, then leave the branch
            // without storing the final state. If used, the break should be
            // the last expression in the branch, any expressions after the break
            // will be skipped

            // `continue` is similar to break, except the loop is not 
            // completely stopped.

            // this.getExecutor().breakBranch();
            // this.setResult(ctx, -1);

            const breakContext = this.getExecutor().getBreakContext();
            const currentResult = this.getResult(breakContext) ?? {};

            this.setResult(breakContext, {
                ...currentResult,
                breakSignal: true,
                continueSignal: ctx.Continue() ? true : false
            });
        }
    }

    visitArray_expr = (ctx: Array_exprContext): void => {
        const array = ctx.data_expr().map(item => {
            return this.visitResult(item);
        });

        this.setResult(ctx, array);
    }

    visitArrayExpr = (ctx: ArrayExprContext): void => {
        const array = ctx.data_expr().map(item => {
            return this.visitResult(item);
        });
        
        this.setResult(ctx, array);
    }

    visitArrayIndexExpr = (ctx: ArrayIndexExprContext): void => {
        const ctxArray = ctx.data_expr(0)!;
        const ctxArrayIndex = ctx.data_expr(1)!;

        const arrayItem = this.visitResult(ctxArray);

        // This will be a numeric value, if it is a valid number.
        const indexValue = this.visitResult(ctxArrayIndex);

        if (!Array.isArray(arrayItem)) {
            throw new RuntimeExecutionError("Invalid array", ctxArray);
        }

        if (!(indexValue instanceof NumericValue)) {
            throw new RuntimeExecutionError("Invalid index value", ctxArrayIndex);
        }

        const indexValueNumber = indexValue.toNumber();

        if (isNaN(indexValueNumber)) {
            throw new RuntimeExecutionError("Invalid index value", ctxArrayIndex);
        }

        if (Array.isArray(arrayItem)) {
            this.setResult(ctx, arrayItem[indexValueNumber]);
        }
    }

    protected setResult(ctx: ParserRuleContext, value: any): void {
        this.resultData.set(ctx, value);
    }

    protected getResult(ctx: ParserRuleContext): any {
        return this.resultData.get(ctx);
    }

    protected linkComponentToCtx(ctx: ParserRuleContext, 
        instance: ClassComponent, creationFlag = true): void {
        // If creationFlag is true, it indicates that the component was created
        // within this ctx.
        
        // If this component is within a loop, then update the component's
        // loop stack property.
        const scope = this.getScope();
        const indexedStack: [ParserRuleContext, number][] = [];

        if (scope.breakStack.length > 0){
            const executor = this.getExecutor();    
            scope.breakStack.forEach(stackCtx => {
                const entry = executor.indexedStack.get(stackCtx)!;
                const { index } = entry;
                indexedStack.push([stackCtx, index]);
            });
        }

        instance.ctxReferences.push({
            ctx,
            indexedStack,
            creationFlag,
            filePath: this.getCurrentFile(),
        });

        this.componentCtxLinks.set(ctx, instance);
    }

    getComponentCtxLinks(): Map<ParserRuleContext, ClassComponent>{
        return this.componentCtxLinks;
    }

    visitResult(ctx: ParserRuleContext): any {
        this.visit(ctx);
        return this.getResult(ctx);
    }

    // Visits the inner/child ctx and stores the result in the parent ctx. 
    passResult(ctx: ParserRuleContext, innerCtx: ParserRuleContext): void {
        // Pass any params on
        const params = this.getResult(ctx);
        if (params){
            this.setResult(innerCtx, params);
        }
        this.setResult(ctx, this.visitResult(innerCtx));
    }

    protected handleImportFile(name: string, 
        importHandling: ImportFunctionHandling,
        throwErrors = true, ctx: ParserRuleContext | null = null, 
        specificImports: string[] = []): ImportLibraryFile {

        name = name.trim();
        const importAlready = this.importedFiles.find(item => {
            return item.id === name;
        });

        if (importAlready) {
            const { importedLibrary: tmpImportedLibrary } = importAlready;

            const alreadyImportedFlag = tmpImportedLibrary.importHandlingFlag;
            const isMergedNamespace = alreadyImportedFlag === ImportFunctionHandling.AllMergeIntoNamespace
                || alreadyImportedFlag === ImportFunctionHandling.SpecificMergeIntoNamespace;
            
            const invalidImportCondition1 =
                alreadyImportedFlag === ImportFunctionHandling.AllWithNamespace &&
                importHandling !== ImportFunctionHandling.AllWithNamespace;

            const invalidImportCondition2 = 
                alreadyImportedFlag !== ImportFunctionHandling.AllWithNamespace &&
                importHandling === ImportFunctionHandling.AllWithNamespace;

            if (invalidImportCondition1 || invalidImportCondition2){
                throw new RuntimeExecutionError(`Namespace import and wildcard/specific imports cannot be mixed: ${name}`, ctx);
            }

            if (isMergedNamespace) {
                // Combined the specific imports
                if (alreadyImportedFlag === ImportFunctionHandling.AllMergeIntoNamespace) {
                    // Do nothing, because all already merged into the namespace
                } else if (alreadyImportedFlag === ImportFunctionHandling.SpecificMergeIntoNamespace && importHandling === ImportFunctionHandling.AllMergeIntoNamespace) {
                    // The incoming import is to merge all, so update the library to merge all instead.
                    tmpImportedLibrary.specifiedImports = [];
                    tmpImportedLibrary.importHandlingFlag = ImportFunctionHandling.AllMergeIntoNamespace;
                    
                } else if (alreadyImportedFlag === ImportFunctionHandling.SpecificMergeIntoNamespace && importHandling === ImportFunctionHandling.SpecificMergeIntoNamespace) {
                    // Combine both specific impors together
                    tmpImportedLibrary.specifiedImports.push(
                        ...specificImports
                    )
                }
            }

            return importAlready;
        }

        let hasError = false;
        let hasParseError = false;
        let pathExists = false;

        const tmpFilePath = this.environment.getAbsPathRelativeToCurrentFolder(name + ".cst");
        const relativeFilePath = 
            this.environment.relative(
                this.environment.getCurrentDirectory(), tmpFilePath);
        this.log('importing path:', tmpFilePath);

        let fileData: string | null = null;
        let filePathUsed: string | null = null;

        try {
            filePathUsed = relativeFilePath;
            if (this.loadedFiles.has(relativeFilePath)){
                fileData = this.loadedFiles.get(relativeFilePath)!;
                pathExists = true;
            }
        } catch (err) {
            this.log('failed to read file');
            pathExists = false;
        }

        let importedLibrary!: ImportedLibrary;

        if (!pathExists) {
            // if path does not exist, then search default libs path
            try {
                const tmpFilePath2 = this.environment.getRelativeToDefaultLibs(name + ".cst");
                this.log('checking default libs: ' + tmpFilePath2);
                filePathUsed = tmpFilePath2;

                if(this.loadedFiles.has(tmpFilePath2)){
                    fileData = this.loadedFiles.get(tmpFilePath2)!;
                    pathExists = true;
                }

            } catch (err) {
                this.log('failed to read file');
                pathExists = false;
            }
        }

        try {
            if (pathExists && filePathUsed) {
                this.log('done reading imported file data');

                const executionStack = this.executionStack;
                const executor = this.getExecutor();

                const executionContextName = name;
                const netNamespace = executor.netNamespace;
                const libraryNamespace = `${BaseNamespace}${name}.`;

                // Create a new context, so that it is easier to track the
                // functions that were created within the imported library.
                const importContext = this.enterNewChildContext(
                    executionStack,
                    executor,
                    executionContextName,
                    {
                        netNamespace,
                        namespace: libraryNamespace,
                    }, [], []);

                // Try to load from cache before running the full parse+visit pipeline
                let loadedFromCache = false;
                let contentHash = '';

                if (this.enableCachedImportsRead) {
                    try {
                        contentHash = computeContentHash(fileData!);
                        const cachedIR = readCache(filePathUsed, contentHash);
                        if (cachedIR !== null) {
                            this.log('cache hit for:', filePathUsed);

                            const parseAndVisit = (miniScript: string, lineOffset: number): ImportFileResult => {
                                return this.onImportFile(this, filePathUsed, 
                                    miniScript, this.onErrorHandler, lineOffset);
                            };

                            importedLibrary = deserializeLibraryScope(
                                cachedIR,
                                name,
                                libraryNamespace,
                                filePathUsed,
                                importHandling,
                                specificImports,
                                importContext,
                                parseAndVisit,
                                
                                () => {
                                    // Use the same import context
                                    executionStack.push(importContext);
                                    return importContext;
                                },
                                () => {
                                    executionStack.pop();
                                },
                                
                                contentHash
                            );

                            loadedFromCache = true;

                            this.log('Done reading from import cache');
                        }
                    } catch (err){
                        // Cache load errors are non-fatal; fall through to normal parse
                        this.log('Error while reading cache: ', err);
                        loadedFromCache = false;
                    }
                }

                if (!loadedFromCache) {
                    const importResult = this.onImportFile(this,
                        filePathUsed, fileData!, this.onErrorHandler);

                    hasError = importResult.hasError;
                    hasParseError = importResult.hasParseError;

                    this.log(`import handling flag: ${importHandling}`);
                    importedLibrary = new ImportedLibrary(name,
                        libraryNamespace,
                        filePathUsed,
                        importResult.tree, importResult.tokens,
                        importContext, importHandling, specificImports, 
                        contentHash);
                    
                    // Library not cached yet (or cache is outdated), so write
                    // to cache later.
                    importedLibrary.writeToCache = true;
                }

                // Close the import context
                executionStack.pop();

                if (specificImports.length > 0){
                    this.log('specific import: ' + specificImports.join(', '));
                }

                const scope = this.getScope();

                // Add the imported library into the scope.
                scope.libraries.set(name, importedLibrary);

                // Add all libraries that were imported within the imported libraries itself
                importedLibrary.context.scope.libraries.forEach((lib, key) => {
                    scope.libraries.set(key, lib);
                });

                // Merges scope so that any sequences (actions) done in the
                // import will also be part of the main script.
                executor.mergeScope(importedLibrary.context.scope, 
                    importedLibrary.libraryNamespace);

                this.checkLibraryInRefdesFile(filePathUsed);
            }
        } catch (err) {
            if (ctx != null) {
                throw err;
                // throw new RuntimeExecutionError("An error occurred while importing file", ctx);
            } else {
                this.log('An error occurred while importing file:', err.message);
            }
        }

        let errorMessage = null;
        
        if (throwErrors && (hasError || hasParseError || !pathExists)) {
            if (!pathExists) {
                errorMessage = `File does not exist: ${name} (${filePathUsed})`
            } else {
                errorMessage =  `Failed to import: ${name}`;
            }
        }

        if (errorMessage !== null && ctx){
            throw new RuntimeExecutionError(errorMessage, ctx);
        }

        // Keep track of already imported files
        const newImportedFile: ImportLibraryFile = {
            id: name.trim(),
            hasError,
            hasParseError,
            pathExists,
            importedLibrary: importedLibrary!
        };

        this.importedFiles.push(newImportedFile);

        return newImportedFile;
    }

    cacheLibraries(): void {
        this.log('caching libraries');

        const libraries = this.getScope().libraries;
        
        // Persist cache for next run
        for (const [libName, library] of libraries) {
            this.log(`checking write flag for library ${library.libraryName}: ${library.writeToCache}`);

            if (library.writeToCache){
                try {
                    const { fileHash } = library;
                    const ir = serializeLibraryScope(library, fileHash);
                    writeCache(library.libraryFilePath, fileHash, ir);
                } catch (err) {
                    this.log(`failed to cache library: ${libName}`);
                    throw new RuntimeExecutionError(`Failed to cache library: ${libName}`);
                }
            }
        }
    }


    checkLibraryInRefdesFile(filePath: string): void{
        return;
    }

    getPathRefdesFile(filePath: string): string {
        return '';
    }

    getRefdesFileAnnotationKey(filePath:string, startLine:number, startColumn:number, 
        stopLine:number, stopColumn:number):string {
        return `${filePath}:${startLine}:${startColumn}:${stopLine}:${stopColumn}`
    }

    visitRoundedBracketsExpr = (ctx: RoundedBracketsExprContext):void => {
        const ctxDataExpr = ctx.data_expr();
        this.visit(ctxDataExpr);
        const innerResult = this.getResult(ctxDataExpr);
        this.setResult(ctx, innerResult);
    }

    protected setupDefinedParameters(
        funcDefinedParameters: FunctionDefinedParameter[], 
        passedInParameters: CallableParameter[], 
        executor: ExecutionContext): void {
        
        // Check if the arguments match up
        for (let i = 0; i < funcDefinedParameters.length; i++) {
            const tmpFuncArg = funcDefinedParameters[i];

            if (i < passedInParameters.length) {
                const tmpPassedInArgs = passedInParameters[i];
                const argValue = unwrapValue(tmpPassedInArgs[2]);

                if (tmpPassedInArgs[0] === 'position') {
                    // If value is passed in as function parameter, then
                    // use it in the scope.
                    const variableName = tmpFuncArg[0];
                    executor.log(
                        'set variable in scope, var name: ',
                        variableName,
                    );

                    executor.scope.setVariable(
                        variableName,
                        argValue,
                    );

                    if (argValue instanceof ClassComponent) {
                        const component  = argValue;

                        // Add the component nets into the local scope
                        for(const [pinNumber, net] of component.pinNets){
                            executor.scope.setNet(component, pinNumber, net);
                        }
                    }
                } else if (tmpPassedInArgs[0] === 'keyword') {
                    const variableName = tmpPassedInArgs[1];
                    executor.log(
                        'set variable in scope, var name: ',
                        variableName
                    );

                    executor.scope.setVariable(
                        variableName,
                        argValue
                    );
                }

            } else if (tmpFuncArg.length === 3) {
                // Value was not provided to function, but a default 
                // value is provided.
                const variableName = tmpFuncArg[0];
                const defaultValue = tmpFuncArg[2];
                executor.log(
                    'set variable in scope, var name: ',
                    variableName,
                );
                executor.scope.setVariable(
                    variableName, defaultValue,
                );
            } else {
                throw `Invalid arguments got: ` + passedInParameters;
            }
        }
    }

    protected runExpressions(executor: ExecutionContext,
        expressions: ExpressionContext[] | Function_exprContext[]): ComplexType {

        let returnValue: ComplexType | null = null;

        // Track this context for a break signal
        const breakContext = executor.getBreakContext();

        // Execute the expressions within the context
        for (let i = 0; i < expressions.length; i++) {
            const expr = expressions[i];

            // The correct executor MUST be on the top/end of the stack!
            this.visit(expr);

            const { breakSignal = false } = this.getResult(breakContext) ?? {};
            if (breakSignal) {
                returnValue = executor.returnValue;
                break;
            }

            // If this flag is set, then do not parse anything further!
            if (executor.stopFurtherExpressions) {
                returnValue = executor.returnValue;
                break;
            }
        }

        return returnValue;
    }

    protected getNetNamespace(executorNetNamespace: string,
        passedNetNamespace: string | null): string {

        let result = executorNetNamespace;

        if (passedNetNamespace !== null && passedNetNamespace.length > 0) {
            // Either user specified '/' or '/_' to indicate the global
            // net namespace
            if (passedNetNamespace === '/' || passedNetNamespace === '_') {
                result = '';
            } else if (passedNetNamespace[0] === '+') {
                if (executorNetNamespace === '/') {
                    result = passedNetNamespace.slice(1)
                } else {
                    result = executorNetNamespace + passedNetNamespace.slice(2);
                }
            } else {
                result = passedNetNamespace;
            }

            result = result + '/';
        }

        return result;
    }

    protected setInstanceParam(object: ClassComponent, trailers: string[], value: any): void {
        const paramName = trailers[0];
        object.setParam(paramName, value);

        this.log2(
            `set instance ${object.instanceName} param ${paramName} to ${value}`);
    }

    protected getInstanceParam<T>(object: ClassComponent, trailers: string[]): T {
        const paramName = trailers[0];
        return object.getParam(paramName) as T;
    }

    protected enterNewChildContext(executionStack: ExecutionContext[],
        parentContext: ExecutionContext,
        executionContextName: string,
        options: NewContextOptions,
        funcDefinedParameters: FunctionDefinedParameter[],
        passedInParameters: CallableParameter[]
    ): ExecutionContext {
        const { 
            netNamespace = "",
            namespace = null,
        } = options;

        // Create a new execution context, so that the commands are executed only
        // within this context. Components and nets will be local to this context for now.
        const currentExecutionContext =
            executionStack[executionStack.length - 1];
        const executionLevel = currentExecutionContext.executionLevel;

        const executionContextNamespace = namespace ?? currentExecutionContext.namespace
            + executionContextName + ".";

        const newExecutor = new ExecutionContext(
            executionContextName,
            executionContextNamespace,
            netNamespace,
            executionLevel + 1,
            this.getExecutor().scope.scopeLevel + 1,
            currentExecutionContext.silent,
            currentExecutionContext.logger,
            currentExecutionContext.warnings,
            parentContext
        );

        // Add the execution context to the end of the execution stack
        executionStack.push(newExecutor);

        // Setup the params in the execution scope if there 
        // are any function parameters

        this.setupDefinedParameters(
            funcDefinedParameters,
            passedInParameters,
            newExecutor
        );

        newExecutor.resolveNet = this.createNetResolver(executionStack);
        newExecutor.resolveComponentPinNet = 
            this.createComponentPinNetResolver(executionStack);

        return newExecutor;
    }

    protected prepareStringValue(value: string): string {
        return value.slice(1, value.length - 1);
    }

    protected throwWithContext(context: ParserRuleContext, messageOrError: string | BaseError): void {
        throwWithContext(context, messageOrError);
    }

    protected validateType(value: any,
        context: ParserRuleContext,
        validateFunction: (value: any) => boolean,
        expectedType: string): boolean {

        if (value === undefined) {
            return false;
        }

        const result = validateFunction(value);
        if (!result) {
            throw new RuntimeExecutionError(`Invalid ${expectedType}`, context);
        }

        return result;
    }

    protected validateString(value: any, context: ParserRuleContext): void {
        this.validateType(value, context, (val) => {
            return typeof val === 'string';
        }, 'string');
    }

    protected validateBoolean(value: any, context: ParserRuleContext): void {
        this.validateType(value, context, (val) => {
            return typeof val === 'boolean';
        }, 'boolean');
    }

    protected validateNumeric(value: any, context: ParserRuleContext): void {
        this.validateType(value, context, (val) => {
            return (val instanceof NumericValue);
        }, 'numeric value');
    }

    enterFile(filePath: string): void {
        this.log(`enter file: ${filePath}`);
        this.filePathStack.push(filePath);
    }

    exitFile(): void {
        this.log(`exit file: ${this.getCurrentFile()}`);
        this.filePathStack.pop();
    }

    // Returns the complete absolute filepath
    getCurrentFile(): string {
        return this.filePathStack[this.filePathStack.length - 1];
    }
}

export type OnErrorHandler = 
    (message: string, context: ParserRuleContext, e?: any) => void;

type ImportLibraryFile = {
    id: string,
    hasError: boolean,
    hasParseError: boolean,
    pathExists: boolean,
    importedLibrary: ImportedLibrary
}

export type ImportFileResult = {
    hasError: boolean;
    hasParseError: boolean;
    tree: ScriptContext;
    tokens: CommonTokenStream
}