import { ParseTreeVisitor, TerminalNode } from 'antlr4';
import {
    Add_component_exprContext,
    Assignment_exprContext,
    At_blockContext,
    At_block_pin_exprContext,
    At_block_pin_expression_complexContext,
    At_block_pin_expression_simpleContext,
    At_component_exprContext,
    Branch_blocksContext,
    Break_keywordContext,
    Component_select_exprContext,
    Create_component_exprContext,
    Data_exprContext,
    ExpressionContext,
    Function_args_exprContext,
    Function_call_exprContext,
    Function_def_exprContext,
    Function_return_exprContext,
    Nested_propertiesContext,
    ParametersContext,
    Pin_select_expr2Context,
    Pin_select_exprContext,
    Property_exprContext,
    Property_key_exprContext,
    ScriptContext,
    Single_line_propertyContext,
    To_component_exprContext,
    Value_exprContext,
    Wire_exprContext,
    Wire_path_exprContext,
} from './antlr/CircuitScriptParser';
import { ExecutionContext } from './execute';
import { ClassComponent, Component } from './objects/Component';
import {
    NumericValue,
    ParamDefinition,
    PercentageValue,
} from './objects/ParamDefinition';
import { PinDefinition, PinIdType } from './objects/PinDefinition';
import { PinTypes } from './objects/PinTypes';
import { ExecutionScope } from './objects/ExecutionScope';

export class MainVisitor extends ParseTreeVisitor<any> {
    // See class CircuitScriptVisitor (generated by antlr4) to find method names

    // Contains the methods here, so that it is function based instead
    // of just lambdas/callbacks...

    indentLevel = 0;
    startingContext: ExecutionContext;
    executionStack: ExecutionContext[];

    // If true, then do not print out anything
    silent = false;

    constructor(silent = false) {
        super();
        this.startingContext = new ExecutionContext('__base__', 0, 0, silent);
        this.executionStack = [this.startingContext];
        this.silent = silent;
    }

    getExecutor(): ExecutionContext {
        return this.executionStack[this.executionStack.length - 1];
    }

    visit(ctx) {
        // The visit method is moved out from ParseTreeVisitor
        // because its implementation is different that the
        // python version.
        if (Array.isArray(ctx)) {
            const allResults = [];
            let result: any = null;

            for (let i = 0; i < ctx.length; i++) {
                // Follow the python version
                if (!this.shouldVisitNextChild(ctx, result)) {
                    return result;
                }

                const child = ctx[i];
                const childResult = child.accept(this);
                allResults.push(childResult);
                result = childResult;
            }

            return result;
        } else {
            return ctx.accept(this);
        }
    }

    visitChildren(ctx) {
        // Moved out from ParseTreeVisitor
        if (ctx.children) {
            return this.visit(ctx.children);
        } else {
            return null;
        }
    }

    shouldVisitNextChild(node, currentResult): boolean {
        // If result is -1, then do no parse further children
        if (currentResult === -1) {
            return false;
        }
        return true;
    }

    visitScript(ctx: ScriptContext): any {
        this.print('===', 'start', '===');
        const result = this.visitChildren(ctx);
        this.print('===', 'end', '===');
        return result;
    }

    visitExpression(ctx: ExpressionContext) {
        return this.visitChildren(ctx);
    }

    visitParameters(ctx: ParametersContext) {
        const dataExpressions = ctx.data_expr_list();
        const keywordAssignmentExpressions = ctx.keyword_assignment_expr_list();

        const returnList = [];

        dataExpressions.forEach((item, index) => {
            const value = this.visit(item);
            returnList.push(['position', index, value]);
        });

        keywordAssignmentExpressions.forEach((item) => {
            const [key, value] = this.visit(item);
            returnList.push(['keyword', key, value]);
        });

        return returnList;
    }

    visitAssignment_expr(ctx: Assignment_exprContext): any {
        const variableName = ctx.ID().toString();

        const value = this.visit(ctx.data_expr());
        if (this.getExecutor().hasFunction(variableName)) {
            throw (
                "Cannot have variable or instance named as function name '" +
                variableName +
                "'"
            );
        }

        if (value instanceof ClassComponent) {
            const instances = this.getExecutor().scope.instances;
            const tmpComponent: ClassComponent = value;

            const oldName = tmpComponent.instanceName;

            // Rename to new name
            tmpComponent.instanceName = variableName;

            instances.delete(oldName);
            instances.set(variableName, tmpComponent);

            this.getExecutor().print(
                `assigned '${variableName}' to new ClassComponent`,
            );
        } else {
            this.getExecutor().scope.variables.set(variableName, value);
        }

        return value;
    }

    visitValue_expr(ctx: Value_exprContext) {
        const integerValue = ctx.INTEGER_VALUE();
        const numericValue = ctx.NUMERIC_VALUE();
        const stringValue = ctx.STRING_VALUE();
        const percValue = ctx.PERCENTAGE_VALUE();

        if (integerValue) {
            return Number(integerValue.toString());
        } else if (numericValue) {
            return new NumericValue(numericValue.toString());
        } else if (stringValue) {
            return this.prepareStringValue(stringValue.toString());
        } else if (percValue) {
            return new PercentageValue(percValue.toString());
        }
    }

    visitPin_select_expr(ctx: Pin_select_exprContext) {
        if (ctx.INTEGER_VALUE()) {
            return Number(ctx.INTEGER_VALUE().toString());
        } else if (ctx.STRING_VALUE()) {
            return this.prepareStringValue(ctx.STRING_VALUE().toString());
        }

        return null;
    }

    visitAdd_component_expr(ctx: Add_component_exprContext) {
        const component: ClassComponent = this.visit(ctx.data_expr());
        this.getExecutor().addComponentExisting(component);
    }

    visitAt_component_expr(ctx: At_component_exprContext) {
        const [component, pin] = this.visit(ctx.component_select_expr());
        this.getExecutor().atComponent(component, pin, true);
    }

    visitTo_component_expr(ctx: To_component_exprContext) {
        ctx.component_select_expr_list().forEach((item) => {
            const [component, pin] = this.visit(item);
            this.getExecutor().toComponent(component, pin, true);
        });
    }

    visitComponent_select_expr(ctx: Component_select_exprContext) {
        let component: Component | null = null;
        let pinId: number | string | null = null;

        if (ctx.data_expr()) {
            component = this.visit(ctx.data_expr());
        } else {
            component = this.getExecutor().scope.currentComponent;
        }

        if (ctx.pin_select_expr()) {
            pinId = this.visit(ctx.pin_select_expr());
        }

        return [component, pinId];
    }

    visitBranch_blocks(ctx: Branch_blocksContext) {
        this.getExecutor().enterBranches();

        const branches = ctx.branch_block_inner_list();
        branches.forEach((branch, index) => {
            this.getExecutor().enterBranch(index);

            this.visit(branch);

            this.getExecutor().exitBranch(index);
        });

        this.getExecutor().exitBranches();
    }

    visitBreak_keyword(ctx: Break_keywordContext): number {
        // When the break keyword is encountered inside a branch, then leave the branch
        // without storing the final state. If used, the break should be
        // the last expression in the branch, any expressions after the break
        // will be skipped

        this.getExecutor().breakBranch();
        return -1;
    }

    visitCreate_component_expr(ctx: Create_component_exprContext) {
        const properties = new Map<string, any>();

        ctx.property_expr_list().forEach((item) => {
            const result: Map<string, any> = this.visit(item); // Map should be returned

            for (const [key, value] of result) {
                properties.set(key, value);
            }
        });

        const pins: PinDefinition[] = this.parseCreateComponentPins(
            properties.get('pins'),
        );
    
        // Use a unique instance name in the context for now
        let instanceName = this.getExecutor().getUniqueInstanceName('');

        const propParams = properties.get('params');
        const params: ParamDefinition[] =
            this.parseCreateComponentParams(propParams);

        if (params.length > 0) {
            // Always append the first value
            // to the generated name.
            const firstParam = params[0];
            const paramValue = firstParam.paramValue;
            let appendValue = paramValue.toString();

            if (paramValue instanceof NumericValue) {
                appendValue = paramValue.value;
            }

            instanceName += '_' + appendValue;
        }

        let arrangeProps = null;
        if (properties.has('arrange')) {
            arrangeProps = properties.get('arrange');
        }

        let displayProp = null;
        if (properties.has('display')) {
            displayProp = properties.get('display');
        }

        return this.getExecutor().createComponent(instanceName, pins, params, arrangeProps, displayProp);
    }

    visitProperty_expr(ctx: Property_exprContext): Map<string, any> {
        const keyName = this.visit(ctx.property_key_expr());
        const value = this.visit(ctx.property_value_expr());

        const map = new Map<string, any>();
        map.set(keyName, value);

        return map;
    }

    visitSingle_line_property(ctx: Single_line_propertyContext) {
        let value;
        if (ctx.data_expr_list().length === 1) {
            value = this.visit(ctx.data_expr(0));
        } else {
            value = [];
            ctx.data_expr_list().forEach((item) => {
                value.push(this.visit(item));
            });
        }

        return value;
    }

    visitNested_properties(ctx: Nested_propertiesContext) {
        const result = new Map<string, any>();
        ctx.property_expr_list().forEach((item) => {
            const property: Map<string, any> = this.visit(item);

            // Get out all items, by default
            for (const [key, value] of property) {
                result.set(key, value);
            }
        });

        return result;
    }

    visitProperty_key_expr(ctx: Property_key_exprContext) {
        if (ctx.ID()) {
            return ctx.ID().toString();
        } else if (ctx.INTEGER_VALUE()) {
            return Number(ctx.INTEGER_VALUE().toString());
        } else if (ctx.STRING_VALUE()) {
            return this.prepareStringValue(ctx.STRING_VALUE().toString());
        }
    }

    pinTypesList: string[] = [
        PinTypes.Any,
        PinTypes.Input,
        PinTypes.Output,
        PinTypes.IO,
        PinTypes.Power,
    ];

    visitData_expr(ctx: Data_exprContext) {
        let value;
        if (ctx.value_expr()) {
            value = this.visit(ctx.value_expr());
        } else if (ctx.ID()) {
            const idName = ctx.ID().toString();
            const scope = this.getExecutor().scope;

            if (scope.instances.has(idName)) {
                value = scope.instances.get(idName);
            } else if (scope.variables.has(idName)) {
                value = scope.variables.get(idName);
            } else if (this.pinTypesList.indexOf(idName) !== -1) {
                // Not sure if just returning the string is enough...
                value = idName;
            } else {
                throw "Could not find variable '" + idName + "'";
            }
        } else if (ctx.function_call_expr()) {
            const functionCallReturn = this.visit(ctx.function_call_expr());
            // This is the returned component from the function call
            value = functionCallReturn[2];
        } else if (ctx.assignment_expr()) {
            value = this.visit(ctx.assignment_expr());
        } else if (ctx.create_component_expr()) {
            value = this.visit(ctx.create_component_expr());
        }

        return value;
    }

    visitFunction_args_expr(ctx: Function_args_exprContext): string[] {
        // Returns list of param names
        const argumentNames = [];
        ctx.ID_list().forEach((item) => {
            argumentNames.push(item.toString());
        });

        return argumentNames;
    }

    visitFunction_def_expr(ctx: Function_def_exprContext) {
        const functionName = ctx.ID().toString();

        // These are the defined arguments for the function
        let functionArgs: string[] | null = null;
        if (ctx.function_args_expr()) {
            functionArgs = this.visit(ctx.function_args_expr());
        }

        const executionStack = this.executionStack;

        const functionCounter = { counter: 0 };

        const resolveFunction = (functionName: string) => {
            // search through the execution stack in reverse to find if the func_name exists
            this.print('find function', functionName);
            const reversed = [...executionStack].reverse();
            reversed.forEach((context) => {
                if (context.hasFunction(functionName)) {
                    return context.getFunction(functionName);
                }
            });

            return null;
        };

        const __runFunc = (passedInArgs) => {
            // Create a new execution context, so that the commands are executed only
            // within this context. Components and nets will be local to this context for now.

            const executionContextName =
                functionName + '_' + functionCounter['counter'];
            functionCounter['counter'] += 1;

            const currentExecutionContext =
                executionStack[executionStack.length - 1];
            const executionLevel = currentExecutionContext.executionLevel;

            const newExecutor = new ExecutionContext(
                executionContextName,
                executionLevel + 1,
                this.getExecutor().scope.indentLevel + 1,
                currentExecutionContext.silent,
            );

            newExecutor.resolveFunction = resolveFunction;

            // Add the execution context to the end of the execution stack
            executionStack.push(newExecutor);

            // setup the params in the execution scope if there are any function arguments
            if (functionArgs) {
                if (passedInArgs === null) {
                    throw `Function '${functionName}' expects arguments`;
                }

                passedInArgs.forEach((item) => {
                    if (item[0] === 'position') {
                        // Only parse position arguments for now
                        const position = item[1];

                        if (position < functionArgs.length) {
                            const variableName = functionArgs[position];
                            newExecutor.print(
                                'set variable in scope, var name: ',
                                variableName,
                            );
                            newExecutor.scope.variables.set(
                                variableName,
                                item[2],
                            );
                        } else {
                            throw 'Invalid function parameter';
                        }
                    }
                });
            }

            let returnValue = null;

            // Execute the expressions within the context
            const expressionList = ctx.function_expr_list();
            for (let i = 0; i < expressionList.length; i++) {
                const expr = expressionList[i];
                this.visit(expr);

                // If this flag is set, then do not parse anything further!
                if (newExecutor.stopFurtherExpressions) {
                    returnValue = newExecutor.returnValue;
                    break;
                }
            }

            // Function execution is completed, get the last executor
            const lastExecution = executionStack.pop();

            // self.dump_scope(last_execution.scope)

            // Merge what ever was created in the scope with the outer scope
            const nextLastExecution = executionStack[executionStack.length - 1];
            nextLastExecution.mergeScope(
                lastExecution.scope,
                executionContextName,
            );

            // Return the last execution context and the final return value of the function
            return [lastExecution, returnValue];
        };

        this.getExecutor().createFunction(functionName, __runFunc);
    }

    visitFunction_return_expr(ctx: Function_return_exprContext) {
        this.getExecutor().print('return from function');
        const returnValue = this.visit(ctx.data_expr());

        this.getExecutor().stopFurtherExpressions = true;
        this.getExecutor().returnValue = returnValue;
    }

    visitFunction_call_expr(ctx: Function_call_exprContext) {
        this.getExecutor().printPoint();

        let parameters = null;
        if (ctx.parameters()) {
            parameters = this.visit(ctx.parameters());
        }

        const functionName = ctx.ID().toString();
        const [executionContext, returnResult] =
            this.getExecutor().callFunction(functionName, parameters);

        this.getExecutor().printPoint();

        return [executionContext, functionName, returnResult];
    }

    visitPin_select_expr2(ctx: Pin_select_expr2Context) {
        if (ctx.STRING_VALUE()) {
            return this.prepareStringValue(ctx.STRING_VALUE().toString());
        } else if (ctx.INTEGER_VALUE()) {
            return Number(ctx.INTEGER_VALUE().toString());
        }
    }

    visitAt_block_pin_expr(ctx: At_block_pin_exprContext) {
        const atPin = this.visit(ctx.pin_select_expr2());

        const currentComponent = this.getExecutor().scope.currentComponent;
        const currentPin = this.getExecutor().scope.currentPin;

        this.getExecutor().atComponent(currentComponent, atPin, true);

        this.getExecutor().print('at block pin expressions');

        if (ctx.at_block_pin_expression_simple()) {
            this.visit(ctx.at_block_pin_expression_simple());
        } else if (ctx.at_block_pin_expression_complex()) {
            this.visit(ctx.at_block_pin_expression_complex());
        }

        this.getExecutor().print('end at block pin expressions');

        // Go back to the original position
        this.getExecutor().atComponent(currentComponent, currentPin);
    }

    visitAt_block(ctx: At_blockContext) {
        this.getExecutor().print('entering at block');

        this.visit(ctx.at_component_expr());

        const currentComponent = this.getExecutor().scope.currentComponent;
        const currentPin = this.getExecutor().scope.currentPin;

        this.getExecutor().scope.indentLevel += 1;

        ctx.at_block_expressions_list().forEach(expression => {
            this.visit(expression);
        });

        this.getExecutor().scope.indentLevel -= 1;

        // Once all done, then restore
        this.getExecutor().scope.currentComponent = currentComponent;
        this.getExecutor().scope.currentPin = currentPin;

        this.getExecutor().print('leaving at block');
    }

    visitAt_block_pin_expression_simple(ctx: At_block_pin_expression_simpleContext) {
        if (ctx.expression()) {
            // Handle any expressions within
            this.visit(ctx.expression());
        } else if (ctx.NOT_CONNECTED()) {
            // Do nothing
            return;
        }
    }

    visitAt_block_pin_expression_complex(ctx: At_block_pin_expression_complexContext) {
        ctx.expression_list().forEach(item => {
            this.visit(item);
        })
    }

    visitWire_expr(ctx: Wire_exprContext): void {
        const segments: [string, number][] = [];

        const ID_list = ctx.ID_list();
        const integer_list = ctx.INTEGER_VALUE_list();

        const acceptedDirections = ['left', 'right', 'up', 'down']

        ID_list.forEach((item, index) => {
            const direction = item.getText();
            if (acceptedDirections.indexOf(direction) !== -1){
                const integerValue = this.parseIntegerValue(integer_list[index]);
                segments.push([direction, integerValue]);
            }
        });

        this.getExecutor().addWire(segments);
    }


    pinTypes = [
        PinTypes.Any,
        PinTypes.IO,
        PinTypes.Input,
        PinTypes.Output,
        PinTypes.Power,
    ];

    private parseCreateComponentPins(
        pinData: number | Map<string, any>,
    ): PinDefinition[] {
        const pins: PinDefinition[] = [];

        if (typeof pinData === 'number') {
            const lastPin = pinData;
            for (let i = 0; i < lastPin; i++) {
                const pinId = i + 1;
                pins.push(
                    new PinDefinition(pinId, PinIdType.Int, pinId.toString()),
                );
            }
        } else if (pinData instanceof Map) {
            for (const [pinId, pinDef] of pinData) {
                let pinIdType = PinIdType.Int;
                let pinType = PinTypes.Any;
                let pinName: string | null = null;
                let altPinNames: string[] = [];

                if (typeof pinId === 'string') {
                    pinIdType = PinIdType.Str;
                }

                if (Array.isArray(pinDef)) {
                    const firstValue = pinDef[0];

                    // Check if firstValue matches a pin type
                    if (this.pinTypes.indexOf(firstValue) !== -1) {
                        // First value matches a pin type
                        pinType = firstValue;
                        pinName = pinDef[1];

                        if (pinDef.length > 2) {
                            altPinNames = pinDef.slice(2);
                        }
                    } else {
                        pinName = pinDef[0];
                        if (pinDef.length > 1) {
                            altPinNames = pinDef.slice(1);
                        }
                    }
                } else {
                    pinName = pinDef;
                }

                pins.push(
                    new PinDefinition(
                        pinId,
                        pinIdType,
                        pinName,
                        pinType,
                        altPinNames,
                    ),
                );
            }
        }

        return pins;
    }

    private parseCreateComponentParams(
        params: Map<string, any>,
    ): ParamDefinition[] {
        const result = [];
        if (params) {
            for (const [key, value] of params) {
                result.push(new ParamDefinition(key, value));
            }
        }

        return result;
    }

    private prepareStringValue(value: string): string {
        return value.slice(1, value.length - 1);
    }

    private parseIntegerValue(token: TerminalNode): number {
        return Number(token.toString());
    }

    protected print(...params: any[]): void {
        if (this.silent) {
            return;
        }

        const indentOutput = ''.padStart(this.indentLevel * 4, '    ');
        const indentLevelText = this.indentLevel.toString().padStart(3, ' ');

        const args = ['[' + indentLevelText + ']', indentOutput, ...params];
        console.log.apply(null, args);
    }

    dump2() {
        const instances = this.getExecutor().scope.instances;
        const items = [];

        for (const [instanceName, instance] of instances) {
            const pinNets = this.resolveNets(
                this.getExecutor().scope,
                instance,
            );

            const componentItem = {
                name: instanceName,
                pins: {},
            };

            pinNets.forEach((item) => {
                componentItem.pins[item.pin.id] = item.netName;
            });

            items.push(componentItem);
        }

        return items;
    }

    getGraph() {
        const sequence = this.getExecutor().scope.sequence;
        const nets = this.getExecutor().scope.getNets();

        return {
            sequence,
            nets,
            components: Array.from(this.getExecutor().scope.instances.values())
        };
    }

    private resolveNets(
        scope: ExecutionScope,
        instance: Component,
    ): { pin: PinDefinition; netName: string }[] {
        // Returns the list of nets that the component pins are
        // connected to.

        const result = [];

        for (const [pinId, pin] of instance.pins) {
            let netName = 'NO_NET';

            if (scope.hasNet(instance, pinId)) {
                netName = scope.getNet(instance, pinId).name;
            }

            result.push({
                pin: pin,
                netName: netName,
            });
        }

        return result;
    }
}
